### ISSUE TITLE
13.40.14ex (m15) - Error when launching with or opening previous profiles

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#100]
**Edit: Appears linked to Issue #101**

Tried launching m15 with the previously running profile, triggered the following error and Crashed To Desktop:

![image](https://github.com/user-attachments/assets/d751bcfa-c6fc-40f9-b993-cecfa8701e44)

![image](https://github.com/user-attachments/assets/a800ee52-14fc-4304-916c-8445493bdb78)

Opening m15 with a blank profile and loading the profile in JG Ex triggers the same error, without crash to desktop but all device tabs are removed.

Blank profile:
![image](https://github.com/user-attachments/assets/27347537-a6e2-434b-a389-1e779b16b5d0)

Previous profile:
![image](https://github.com/user-attachments/assets/8c78d2c4-2a48-424e-b4a4-e17bf243e37f)

**Comment by Lolo401** [comment]
Appears linked to a specific remap action in my profile, older profiles work just fine.

**Comment by muchimi** [comment]
Fixed in m17.

**Comment by muchimi** [comment]
Sorry fixed in m16.
