### ISSUE TITLE
13.40.14ex (m15) - [Linked to previous issue], Response curves cause JG to Crash

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#101]
While investigating the previous issue, it was noticed that adding response curves might be the cause.  I have however opened this as another issue, feel free to delete / merge as required.

(1) Opened a blank profile,
(2) Mapping a response curve to an axis caused the following errors:

![image](https://github.com/user-attachments/assets/f054c648-9003-4728-9aa5-b4638fda18ab)
![image](https://github.com/user-attachments/assets/9eaf222e-a15f-4fca-97d9-b01cfa8c5145)

Acknowledging the errors resulted in a response curve icon being displayed in the axis box but a blank action field:
![image](https://github.com/user-attachments/assets/a2f7c9d3-86f6-4321-8451-39138767be5f)
![image](https://github.com/user-attachments/assets/b15cffc2-86c7-492b-b305-845fdd477d8f)

**Comment by muchimi** [comment]
Resolved in m17
