### ISSUE TITLE
13.40.14ex (m15) - Right clicking on an existing range gate causes an error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#102]
Appears to be nuisance only.

When an existing gate in a gated axis action was right clicked, the following error would pop up:
![image](https://github.com/user-attachments/assets/eccb96fc-b6e7-4b17-8e2c-99a12d62ff37)

Does not appear to impact functionality.

**Comment by muchimi** [comment]
Fixed in m16
