### ISSUE TITLE
13.40.15ex (m15) - Nesting two gated axis causes crash to desktop

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#103]
While testing the gates axis function, it was realized that gated axis can be selected as a range action:

https://github.com/user-attachments/assets/a1b92e6a-d139-411a-9c68-c3d8aed8665b

Adding another gated axis inside a range of a gated axis cause JG Ex to crash to desktop after 1-2 seconds.  This is an edge case and would probably only occur because of an unintentional selection by the user.  There is no value in nesting gated axis.

**Comment by muchimi** [comment]
More research will need to go into this as I'm not able to duplicate it.

**Comment by muchimi** [comment]
The intent is not to nest multiple gated axes together 😊  I will look into preventing this in a future release.
This said, a couple of fixes: first, the hard crash with QT is resolved (by not using the QT built-in sliders - for some reason, these and Python do not like each other a bit).  
The other is the conditions are all separate "container" containers now and are independent.
