### ISSUE TITLE
13.40.14ex (m15) - Range events in Gated Axis do not work and cause error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#104]
The gated axis feature was tested using a blank profile.
A gated axis was set on the X axis of a device and a third gate was created to obtain two ranges.
The 'Use default range' was unboxed to setup an action when the axis is inside range 1.
![image](https://github.com/user-attachments/assets/994538d6-d4f1-4e74-8093-ff0c2112e318)

Vjoy1/button1 was set to be activated when the axis would be inside range 1:
![image](https://github.com/user-attachments/assets/1cdaf5c3-b4fb-460f-aa88-e6e73aae7634)

The input viewer was used to validate the range.
When the axis crossed the range, the following error was displayed and VJoy1/Btn1 was not activated:
![image](https://github.com/user-attachments/assets/6f20f803-734e-44b9-a50d-1fce599ed228)

**Comment by muchimi** [comment]
That's a great catch - Virtual buttons don't understand nested containers - and I didn't realize the legacy remap would use a virtual button in that mode.  Researching how to make virtual buttons compatible.

**Comment by muchimi** [comment]
Fixed in m16.  NOTE: must use Range Enter condition for virtual buttons if you want them released when the input exits the range.  Tested with the legacy remap that uses virtual buttons.
