### ISSUE TITLE
13.40.14ex (m15) - Gated axis - Editing Gate actions causes an error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#105]
A third gate was created in the Gated Axis action.  Clicking on the preferences wheel next to the gate caused the following error:
![image](https://github.com/user-attachments/assets/d4c9a940-16b8-475d-8847-e002e04142ad)

It was impossible to set an action for the gate.

**Comment by Lolo401** [comment]
Additional information:

The procedure was re-attempted after closing and reopening JG.  This time, JG Ex crashed to desktop without any pop-up.

**Comment by muchimi** [comment]
Fixed in m16
