### ISSUE TITLE
13.40.14ex (m18) - Runtime Mode status bar does not indicate the correct mode.

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#108]
This was tested with a blank profile on m18.  Two modes were created.  2 buttons were mapped to Switch Mode.  Another button was mapped to cycle mode. 

After activating the profile, the mode switch was correctly observed in the input viewer, however, the runtime Mode was not updated in the status bar.

![image](https://github.com/user-attachments/assets/b2899280-3717-401f-97b8-8fc4572a3bcb)

**Comment by muchimi** [comment]
Resolved in m20.  Mode changes will update the status bar, as will mode renames/edits (when the dialog closes).
