### ISSUE TITLE
13.40.14ex (m18) - Gated axis - Pushing the Add button triggers an error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#109]
The following error was encountered anytime the Add button was depressed:

![image](https://github.com/user-attachments/assets/91965990-3a7d-4553-b25e-c1e9f5cd49a8)

**Comment by Lolo401** [comment]
Additional information:

This only happens when using the Add button next to Set Gate count.
![image](https://github.com/user-attachments/assets/c7325b8d-3c80-419e-8bcc-efe23c5bb603)

Using the Add button (no label) next to the gates correctly creates a gate at the current axis location.

**Comment by muchimi** [comment]
Resolved in m19
