### ISSUE TITLE
Cannot select vJoy as Input

### ISSUE THREAD

**Issue by wheeliemonster** [muchimi/JoystickGremlinEx#11]
Hi,

Thanks for your efforts developing this. It looks really useful as I have a use case for sending Joystick Gremlin across the network to my gaming machine.
However, I am running into a problem whereby I cannot select a vJoy 1 as an input device. The UI shows me clicking on the box, but never confirms it with a tick and doesn't "move" the vJoy 1 tab like the original software does.
This works fine in the original version I have installed.

Thanks again and hopefully you can find the problem :)

**Comment by wheeliemonster** [comment]
Just wanted to add to this. Seemingly, enabling this in the original version has somehow pulled through into "EX" now, so it seems to be working. So, it's not impeding my progress at this point - but still something you may want to look into?

**Comment by muchimi** [comment]
Thanks - is there anything in the log that would point to an error?  While it works fine on my test devices, there may be something I didn't account for or possibly an exception when it tries to access the device.  The detection part of the code has not changed so this could be UI related.   A screenshot or log would help pinpoint this.

**Comment by wheeliemonster** [comment]
I'll check logs tomorrow. It was the first thing I tried to do after running it, so maybe it's something to do with having a blank profile, etc.
One thing I did notice is that on first run it looks for your JG config.json. As I hadn't installed JG on this machine, JGEX crashed on first run. I had to install JG to get it to generate the config.json which then allowed JGEX to read it and run successfully.

**Comment by muchimi** [comment]
Found another QT upgrade challenge - fixed - new version inbound that enables the checkboxes in the settings page for vjoy.
This issue occured in two spots I found in the code.
I'm now able to check or uncheck vjoy as input in the settings dialog which should (here's that word again) enable you to use the checked vjoy devices as input into JGEX.

**Comment by wheeliemonster** [comment]
Thanks, and apologies for not sending logs. Family life got in the way... 👍🏻

**Comment by muchimi** [comment]
Don't I know it lol.   The version posted yesterday made the input checkboxes functional again - hopefully, it resolves what you were experiencing.

**Comment by muchimi** [comment]
Closing this pending further feedback.
