### ISSUE TITLE
13.40.14ex (m18) - Deleting all but one gates results in an unsolvable situation

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#110]
Several gated were added.  They were all individually deleted until only one remained:
![image](https://github.com/user-attachments/assets/f1be38f1-5920-4e26-a77d-9d9cb970f82e)

After that, it was no longer possible to add any new gate, 
- pushing the Add button would result in the previously mentioned issue.
- Trying to right click on the axis to create a new gate would open the Gate 1 Configuration window.
- Clicking the Set button with a gate count value would trigger the following error:
![image](https://github.com/user-attachments/assets/b0c521c5-4a1f-45e7-ae50-a30612c12088)

- Clicking Normalize or Normalize (reset) would trigger the following error:
![image](https://github.com/user-attachments/assets/9efe1dc8-731e-4519-8dd8-9b5bc167e770)

I was unable to find a workaround to return to a normal situation.

**Comment by Lolo401** [comment]
Additional information:

Deleting the container resulted in a Crash To Desktop

**Comment by Lolo401** [comment]
Well, strike my last.  Deleting the container a second time caused a CTD.

**Comment by muchimi** [comment]
Added check to ensure two gates remain.  Fixed in m19.
