### ISSUE TITLE
13.40.14ex (m18) - Deleting a mode while it is the current Edit mode results in an error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#111]
Two modes were created, default and Test 2.
A single remap was created with the Test 2 Mode being modified.
The mode was then deleted while being edited.  The status bar keeps mentioning Test 2 as the edit mode.
Clicking any device button resulted in the following error:

![image](https://github.com/user-attachments/assets/b858ac1b-bea3-4553-9c8c-69fb486f54c9)

After acknowledging the error, the keybind for Test 2 was still being displayed with 'Default' shown in the Profile Edit Mode window.  However, the status bar Edit Mode was still indicating Test 2.

Deleting a mode with keybinds should prompt the user with a warning that all keybinds will be lost, it should revert back to either the parent or the previous mode and the status bar should reflect the status accordingly. (recommendation)

**Comment by muchimi** [comment]
Resolved in m20 - added confirm box to delete in mode editor.
If the mode was active (either edit or runtime) - it will change to the first top level mode.
