### ISSUE TITLE
13.40.14ex (m18) - Deleting a mode does not work.  

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#112]
While investigating issue #111, Test 2 was deleted, the Profile Edit Mode window correctly displayed only Default as available modes.  The profile was saved, JG Ex was closed and reopened.

Both profiles were again selectable in the Profile Edit Mode.

https://github.com/user-attachments/assets/d42c86cf-bbf8-420a-811f-565fbd3f3980

**Comment by Lolo401** [comment]
Note:
This only happens when the deleted mode is currently active.  The same procedure was performed with Test 2 active and deleting Default.  Everything worked as per design.  Saving and reopening the file correctly resulted in only Test 2 being available.

**Comment by muchimi** [comment]
Resolved in m20 + add confirm box on delete.
