### ISSUE TITLE
13.40.14ex (m22) - Status bar displays incorrect Runtime and Edit mode when switching profiles

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#117]
100% Repro:

A profile was loaded containing different modes (test 1 and test 2.  One mode was set to Run and another to Edit.  Those modes were correctly displayed in the status bar.
![image](https://github.com/user-attachments/assets/c837722a-7e59-4639-9444-9506c634d5ca)

Another profile, containing only the default profile was loaded.
![image](https://github.com/user-attachments/assets/c588fc52-35f4-4df0-9484-b9e1992de43a)

After loading the profile, the status bar kept on displaying the previous Test 1 and Test 2 modes:
![image](https://github.com/user-attachments/assets/612399e3-bbc4-42c6-9969-eff488ac6943)

The problem only manifests itself when the profile is initially opened.  Activating the profile or entering the Manage Mode option menu will correctly reset the runtime and edit modes.

**Comment by muchimi** [comment]
Added a forced status bar refresh on profile load.
Should be up on the next release.

**Comment by muchimi** [comment]
Please confirm the pre-release update fixes this.  Thanks.

**Comment by muchimi** [comment]
Marking resolved as of 13.40.15ex m2
