### ISSUE TITLE
Gated axis Enter / Exit range crash to desktop

### ISSUE THREAD

**Issue by Smuli34** [muchimi/JoystickGremlinEx#118]
I created gated axis with Vjoy keypress when entering / exiting the zone. When I activate the profile and move the axis there is a crash to desktop. Attached is the log file, search "Flight Throttle Quadrant guid={10D03000-4D01-11EF-8001-444553540000}" that is where I had the action:

[Log.txt](https://github.com/user-attachments/files/17006473/Log.txt)

**Comment by muchimi** [comment]
Thank you - one more request - can you attach the actual profile xml - this will show me the exact configuration so I can look at the problem by duplicating your exact config.
There are two errors in the log file, but neither would cause the issue; I thus suspect an issue with QT (QT is the user interface library).

**Comment by muchimi** [comment]
Update that I just tested gated axis with triggered events via keymapEx, remap and vjoyremap without an issue - however this is with the the pre-release candidate.  I plan to make that available later today for testing purposes as this version has a few more bug fixes and more "wiring" tweaks to the UI in 13.40.15ex that may resolve this.

**Comment by muchimi** [comment]
Resolved in 13.40.15.m2
