### ISSUE TITLE
Macro vJoy Axis not showing input for value

### ISSUE THREAD

**Issue by fjdiazt** [muchimi/JoystickGremlinEx#120]
v3_40_14_m22

Value input is missing from Macro vJoy Axis

JoystickGremlin
![image](https://github.com/user-attachments/assets/a585381a-694c-442b-9c23-ef057f2add5f)

JoystickGremlinEX
![image](https://github.com/user-attachments/assets/dba7245a-7494-4b0e-bc60-b95b51cba2c4)

**Comment by muchimi** [comment]
I need to research this one.   Thanks for reporting.

**Comment by muchimi** [comment]
A bug fix was made on a list of VJOY devices in a prior patch that I hope will address this issue.
I'm unable to duplicate this on the current pre-release code.  Feel free to re-open if you have new information after attempting on 13.40.15ex pre-release.  It would be helpful to get a copy of your profile (XML) and the associated log file (log.txt) located in the gremlin ex user folder.  You can locate that folder using the file menu "reveal" menu option that will open a file explorer window at the correct folder location.

We can re-open based on this additional information if the issue re-occurs in the most recent pre-release.  Thanks.
