### ISSUE TITLE
Connecting a generic USB Joystick cause an exception

### ISSUE THREAD

**Issue by fjdiazt** [muchimi/JoystickGremlinEx#122]
v3_40_14_m22

Whenever I connect a generic USB Joystick (VKB Gladiator clone) I get this exception, if I unplug it, exception goes away.

![image](https://github.com/user-attachments/assets/ad307607-74c8-4a06-a5d1-3a23df1631a5)

[system.log](https://github.com/user-attachments/files/17017848/system.log)

Also, that exception is causing the system to overflow and crash if I enable verbose logging.

EDIT: Deleting config.json fixed the issue, but it should be able to self-correct the config values.

**Comment by muchimi** [comment]
Whoops.  That should be fixed in the next patch.
Thank you for reporting.  You can currently bypass this error by disabling automatic device highlight in options - that will bypass the section of code that causes this exception.

**Comment by muchimi** [comment]
Please see if this has been resolved in 13.40.15ex m2.  Thanks.

**Comment by muchimi** [comment]
Going to close this pending new information if the issue would occur again post bug fix.
