### ISSUE TITLE
13.40.15ex (RC1) - Action Description replaced when profile saved

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#124]
The following issue has been observed on .15ex (RC1) and .14ex (m22).  100% repro using blank or existing profiles.

Whenever a profile is saved, the Action Description field gets populated by a string based on the mapped action.  Any user entered description is removed.

https://github.com/user-attachments/assets/bc74ad0a-f094-4415-a73a-a5098c889ab3

Although the feature to auto-populate the description if none has been entered is useful, saving the profile should not override user-entered descriptions.

**Comment by muchimi** [comment]
Looking into this. This is not the intended behavior.

**Comment by muchimi** [comment]
Marking resolved as of 13.40.15ex m2
