### ISSUE TITLE
13.40.15ex m1 - copy paste actions lead to memory leak ?

### ISSUE THREAD

**Issue by Smuli34** [muchimi/JoystickGremlinEx#125]
When using copy and paste the action / containers will eventually end to situation that application does not respond. Also my web browser seems to slow down. Gremlin does not take much CPU time but eats lot of memory (nearly 9000 MB in this case, picture). And increasing without doing anyting.

![memory](https://github.com/user-attachments/assets/f97a9f7b-81fe-4933-a5ef-904fa7595102)

**Comment by muchimi** [comment]
I am not currently able to duplicate but it may have to do with the type of container/action your are cutting/pasting.
Can you share what you are copying in terms of container type and actions?
Have you tried saving the profile after the past, existing GremlinEx, restarting and loading the saved profile to see if the memory leak continues (without cut/paste)?
It sounds odd to me the leak is due by the paste - it's completely possible but we are not copying UI elements, only data, so I suspect this is tied more to a specific container / action.

**Comment by Smuli34** [comment]
Hi Muchimi, I was doing copy/paste a macro event with Vjoy buttons. After reboot and not editing there was no memory leak at all. Easy to try: copy a macro, paste it multiple times and then delete pasted macros. You can see that used memory increased fast (sometimes just keeps increasing without pasting) and when you delete all pasted macros much less memory is freed.
I faced a situation that application stopped responding or was extremely slow after multiple pastes.

**Comment by muchimi** [comment]
I have modified the container copy/paste to avoid a binary copy, which I hope resolves any potential issue with direct and indirect references that may keep memory objects from being collected as garbage. 
The idea is that the container copy/paste operation will now use the exact mechanism to persist data to profiles except do this temporarily in memory, eliminating any pointer references.   
I ran a few tests with some containers containing macros and didn't see a bump in memory usage (outside of a small bump to account for the new data and memory looks stable.
I'll publish the change in the updated m2 patch as soon as I complete some additional tests.

**Comment by muchimi** [comment]
Marking resolved as of 13.40.15ex m2.
The copy/paste no longer uses or holds on to binary objects.
A bit more context on this one: QT keeps duplicate objects in memory for as long as Python keeps a reference to them, direct or indirect.   QT is already very memory hungry, so this change alleviates the issue by no longe keeping complex objects in binary form that hold on to all their QT UI components while in the clipboard even if they are not used except as a data source.
