### ISSUE TITLE
13.40.15ex (m2.1) - Error at launch, impossible to open JG Ex

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#126]
Multiple types of error were encountered when trying to launch JG Ex .15ex (m2.1):
![image](https://github.com/user-attachments/assets/b50a57df-766e-41f6-addb-6e61ce0f9ce7)

![image](https://github.com/user-attachments/assets/99b931f9-e7d1-48d0-9c69-d8e3a87db8b2)

I tried to open JG Ex .15ex (m2.1) with a previous profile being worked on in JG Ex .14ex

**Comment by Lolo401** [comment]
The following error was displayed when launching JG Ex .15ex (m2.1) after closing JG Ex .14ex (m22) with a blank profile:

![image](https://github.com/user-attachments/assets/0a90c278-203e-4c88-b688-b3c56fe1396d)

However, once the error was acknowledged, JG EX .15ex (m2.1) launched.

**Comment by muchimi** [comment]
Of course - works like a champ here :)
Let me see if I can duplicate.

**Comment by Lolo401** [comment]
Of course !

**Comment by muchimi** [comment]
Let me hit you on discord.

**Comment by Lolo401** [comment]
Online

**Comment by muchimi** [comment]
Resolved.
