### ISSUE TITLE
JG Ex 13.40.15ex (m2.5) - Unable to delete action

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#127]
This was tested using a blank profile on m2.5:

Anytime an attempt was made to remove an action, when clicking the X button the following error would get displayed and the action would not get removed:

![image](https://github.com/user-attachments/assets/6a78a2eb-26e3-4866-8502-08a832d6dcde)

**Comment by muchimi** [comment]
Resolved in m2 hotfix 6
