### ISSUE TITLE
JG 13.40.15ex (m2.5) - Gated axis, set gate count results in Uncaught exception

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#128]
The Gated axis feature was tested using a blank profile. The X axis of a device was mapped using Gated Axis. The gate count was set by default to 2.  It was increased to 3 using the up arrow.
The 'Set' Button was pressed to set the third gate.  The following error was displayed:
![image](https://github.com/user-attachments/assets/f1397684-1e00-4d0d-99b6-65443fe12225)

**Comment by muchimi** [comment]
Resolved in m2 hotfix 6
