### ISSUE TITLE
Vjoypulse duration setting not recorded in xml file

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#13]
Hi,

As per the title, it appears that the duration entered when selecting a Pulse button is not being recorded.  Changing the default from 250ms to another value works until JG Ex is closed.  Reopening the file resulted in the value reverting back to 250ms.

Inspecting the xml file using Visual Code Studio has shown that changing the duration value was not recorded.

I am using pulse buttons as a workaround to the tempo issue reported as issue 6.  However the default value of 250ms is too long and results in missed inputs in games like Star Citizen.

Changing the default to 50ms would temporarily fix the problem until the duration value can be recorded in the xml file.

Cheers !

**Comment by Lolo401** [comment]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/080fd97c-b596-42f7-a6f1-9d94d310f303)

After saving results in: 

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/6650ca15-62f6-4049-bb45-16dd10983150)

**Comment by muchimi** [comment]
Bug fix in 13.40.7ex
