### ISSUE TITLE
JG 13.40.15ex (m2.5) - Map to SimConnect, error on mapping

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#130]
The Map to SimConnect was tested on a blank profile.  Whenever the action was added to a button, the following error was displayed:

![image](https://github.com/user-attachments/assets/be073d38-8696-405f-a542-e1068c2afe3e)

**Comment by muchimi** [comment]
This has been resolved in m2 hotfix 6
