### ISSUE TITLE
JG 13.40.15ex (m2.5) - Import profile, Uncaught exception

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#132]
The import profile feature was tested like this:
(1) A blank profile was created using File / New;
(2) A 1:1 mapping was performed on a device;
(3) The profile was saved as 'test.xml'.
(4) The profile was closed.

A new blank profile was created again, the option 'Import Profile' was selected and test.xml was selected.  The following error was displayed:

![image](https://github.com/user-attachments/assets/32e992fd-a85a-4a3a-bc0e-63d716bd4040)

**Comment by muchimi** [comment]
That is unrelated to the import but was triggered by it.
Resolved AFAIK in m2 hotfix 6 by fixing the offending line that I forgot to undo this weekend...

**Comment by muchimi** [comment]
Marking this closed for now.
