### ISSUE TITLE
JG 13.40.15ex (m2.5) - Macro, Mouse button events not executed

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#133]
A macro was created using Left and Right mouse button events.  The profile was saved and run.  Mouse macro events are not being actioned by JG Ex.

![image](https://github.com/user-attachments/assets/6a1084d1-2346-4a4a-a8fd-6f2f7a179faa)

Note: When recording the macro, mouse events are well recognized and recorded. Only during execution are mouse buttons skipped.

**Comment by muchimi** [comment]
Well that looks to be a new very old bug because the last time that code was changed was over a year ago.
Excellent find and resolved in m2 hotfix 6

**Comment by muchimi** [comment]
Marking this closed with hotfix m2.7
