### ISSUE TITLE
JG 13.40.15ex (m2.6) - Action Copy-Paste results in error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#134]
Copy pasting an action inside a container resulted in the following error:

![image](https://github.com/user-attachments/assets/28911629-e99e-4f98-9d47-9511f1a14d78)

Note: Copy-pasting a container does work as intended.

**Comment by muchimi** [comment]
The error is because of an attempt to paste an action that is not suitable for the input - and the call changed.
The message box that should pop up is resolved in hotfix 7.

**Comment by muchimi** [comment]
Marking this closed with hotfix m2.7
