### ISSUE TITLE
JG 13.40.15ex (m3) - VJoyremap not available as Action

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#137]
VJoyremap was not showing up as a selectable option in the action dropdown menu:

![image](https://github.com/user-attachments/assets/c6652fd5-e779-42fb-92d4-062f092718dc)

**Comment by muchimi** [comment]
Scroll issue?
![image](https://github.com/user-attachments/assets/f1960d0f-8e74-4a7a-a3bb-1d02471b0bd5)

**Comment by Lolo401** [comment]
Lol.  Nope.  I checked that multiple times. I tried on buttons and axis.

**Comment by muchimi** [comment]
Was able to duplicate.. Looks like a missing reference.

**Comment by muchimi** [comment]
Yes, identified the culprit...

**Comment by muchimi** [comment]
Sometimes the packager doesn't realize there's a dependency to include in the package because the package is delay loaded.
Resolved in m4.
