### ISSUE TITLE
JG 13.40.15ex (m4.1) - Vjoy Remap Output Curve causes an Uncaught Exception

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#138]
A blank profile was created after a fresh start of JG EX .15 m4.1.  the X Axis of a device was selected and mapped using VJoy Remap:
![image](https://github.com/user-attachments/assets/db9536b6-c0ee-4bec-ab1b-219a1d77c305)

Whenever the button 'Output Curve' was clicked, the following error would get displayed:
![image](https://github.com/user-attachments/assets/ec9d61c3-34c0-41bb-a72a-6355d83f511e)

Debug file:
[dill_debug.txt](https://github.com/user-attachments/files/17351587/dill_debug.txt)

Profile (.txt added to extension):
[test.xml.txt](https://github.com/user-attachments/files/17351599/test.xml.txt)

**Comment by muchimi** [comment]
Does this happen in m4.2?

**Comment by muchimi** [comment]
And the debug file is log.txt, dill is only for the dinput C++ layer.

**Comment by muchimi** [comment]
I think I found one issue if you have input tracking disabled - it's thinking the tracking is enabled when it is not.
Will add a check in m4.4

**Comment by Lolo401** [comment]
Fixed in m4.4
