### ISSUE TITLE
loading Logitech X56 ghost-input-filter plugin fails

### ISSUE THREAD

**Issue by brammmers** [muchimi/JoystickGremlinEx#14]
When the plugin (which works perfectly in the original JoystickGremlin is loaded and configured, version 13.40.2 errors with a generic message:

"Unable to launch user plugin due to an error:". No actual error is listed however.

The user log for the plugin indicates is it actually being loaded though, but JG doesn't like something and stops working properly after the error.

This plugin is the reason I use JG(Ex).

Win10, Python 3.11 x64 installed seperately.
All updates installed.
JG is located in a writable location: "%USERPROFILE%\joystick_gremlin"

**Comment by muchimi** [comment]
Thanks for the report, I shall investigate.  I don't have an X56 but that shouldn't matter.  Can you point me to that plugin code as I'm not sure I understand what this ghost input filter is (is not a standard plugin?)?

The reasons this may happen is a different version of the framework, hookups and python between the original Gremlin and this updated version.  If I can get the code to the plugin, I'll be able to debug it and see where the dragons are.

**Comment by brammmers** [comment]
Thanks! Correct it is non-standard.

The Git repo is here: https://github.com/high-the-memory/ghost-input-filter.git

**Comment by muchimi** [comment]
Ok thanks.  I'll take a look.

**Comment by muchimi** [comment]
Fixed in https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.8ex
Here's the updated file tested in Python 3.11+ used by JGEX (it also works in 3.12 based on an internal test). 

[jgex-ghost-input-filter.zip](https://github.com/muchimi/JoystickGremlinEx/files/14963442/jgex-ghost-input-filter.zip)

**Comment by brammmers** [comment]
Thanks, I'll test it this weekend

**Comment by brammmers** [comment]
Initial testing is good. I don't know if you can do anything about this, but if I start JGEx without my hotas plugged in I get a "device not found" error. However is does mention "user plugin", so I believe it to be the extra script with the issue.

**Comment by muchimi** [comment]
In this case, the plugin script does enumerate the raw devices at profile startup and will generate an error if it cannot find any to map.  This said, it should be a matter of plugging in the HOTAS and starting the profile again to it re-enumerates.
I've on the to-do list to review for another issue the behavior of the code when plugging/unplugging devices while GremlinEx is running so it handles it more gracefully.  The general expectation of the code logic is all your devices are connected (and stay connected!) while GremlinEx is running.

**Comment by brammmers** [comment]
Hi, I'm having trouble with this plugin again on the latest GremlinEx build. Lots of strange errors when trying to configure it, which completely breaks the UI and I have to edit the XML to get back to a working state.
