### ISSUE TITLE
JG 13.40.15ex (m4.4) - Output response curves do not work as intended

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#141]
(1) A single blank profile was created with a single axis remapped to Vjoy 1 / Axis 1:
![image](https://github.com/user-attachments/assets/dc5e9474-f68f-40cc-8cf5-4948b598a12a)

(2) the output curve was inverted:
![image](https://github.com/user-attachments/assets/f481b868-3a83-449d-8138-3061a988b4b4)

(3) The profile was run with the input viewer displayed on the side:
![image](https://github.com/user-attachments/assets/7e25c50d-cddf-45f2-addb-6f0c45062feb)
The output value is not inverted.

The same behavior was observed regardless of the output curve settings.  Several 'goofy' curves were tested, including the presets.  It always resulted in as standard non linear response, bypassing the output curve.

**Comment by muchimi** [comment]
I have wired the curve output of the plugin into the action chain so it will not be standalone anymore.  This means that the output value of one curve should feed into the input value of another curve - I duplicated your scenario and I think was able to produce the anticipated output in m4.5.

**Comment by muchimi** [comment]
Closing the issue - we can re-open based on further feedback on this topic if hotfix 5 did not correct the issue.
