### ISSUE TITLE
JG 13.40.15ex (m4.4) - Output response curve, applying a preset curve after changing curve type results in an Uncaugth Exception

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#142]
The curve presets were tested in three different conditions:
(1) Using cubic spline (default) type:  the preset was displayed.
(2) Using cubic Bezier spline type: the preset was displayed.

(3) However, anytime the curve type was changed back from Bezier to default and a preset applied, it would result in the following error:
![image](https://github.com/user-attachments/assets/6add4012-b096-4d03-8cfd-e4cb5c4c62b8)

Video recording of the issue:

https://github.com/user-attachments/assets/73845f7d-9a15-43e8-bca0-43cab80fd0ea

**Comment by muchimi** [comment]
Resolved in m4 hotfix 5

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m4_5.zip

**Comment by muchimi** [comment]
Closing the issue - we can re-open based on further feedback on this topic if hotfix 5 did not correct the issue.
