### ISSUE TITLE
JG 13.40.15ex (m4.4) - Output response curves, moving the center control point (0,0) results in the curve being erased

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#143]
Any time the center control point is moved of the 0,0 position, the changes would not get applied to the curve.

Video Recording:

https://github.com/user-attachments/assets/016f84bd-f257-4b67-8924-781f3b341478

**Comment by muchimi** [comment]
I am not able to duplicate this but it may be because of another bug in the UI when the values were zero causing a division by zero in the spline computation.
See if hotfix 5 changes this behavior.  Thanks.

**Comment by muchimi** [comment]
Closing the issue - we can re-open based on further feedback on this topic if hotfix 5 did not correct the issue.
