### ISSUE TITLE
JG Ex 13.40.15ex (m4.4) - Legacy response curves not displaying correctly when moving center control point off center

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#144]
This was noticed when investigating the previously reported issues:  I have the following curve setup on my rudder pedals to split the merge the two pedals on a single axis:
![image](https://github.com/user-attachments/assets/1843f436-00ed-4c3a-b6d6-23c40dbc2725)

This results in the R pedal being used for forward movements and L pedal for back movements on the same axis.

When opening the xml profile with those cuves, the profile was working as intended, however the response curve window was displaying only a standard linear curve.  Weird.

Here is a video of the issue using a blank profile.  As can be seen on the last section of the video, the profile still works as intended but a flat curve is now displayed after loading the profile.

https://github.com/user-attachments/assets/ec9ce1c9-156a-40aa-bf23-884cf66c1ee1

**Comment by muchimi** [comment]
The code for the response curve was not changed except to add the repeater option (show input axis enabled in options) which shows where on the curve the input is and the values returned by the curve.  I'd like the test profile so I can make sure I duplicate your settings.  Also, if you would, enable this option so we can see what it's doing "live" on the curve.

![image](https://github.com/user-attachments/assets/9fbfee70-5969-43ba-b699-2ee6ef8c4519)


Also: your particular scenario is an interesting use of curves.  I accomplish (what I think is the same thing) by using the merge feature (previously I did this in a user plugin but now built-in vjoy-remap).
Axis 1: left toe brake -> vjoy remap -> merge axis mode -> Axis 2 right toe brake -> merge mode "center".  You can invert depending on what direction you want to be forward/back.  I use this in SC not for the throttle but for strafe up/down.

**Comment by muchimi** [comment]
I have updated some of the UI behaviors for both control points and handles in hotfix 5.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m4_5.zip
