### ISSUE TITLE
JG 13.40.15ex (m4.8) - VJoy Remap, Axis to Button causes Uncaught exception at profile start

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#146]
The axis to button was tested by mapping a single axis to two different buttons using L-Half and H-Half options:
![image](https://github.com/user-attachments/assets/9b8239ee-e119-4147-95bb-54fc606b478f)
![image](https://github.com/user-attachments/assets/93d49ba3-f81e-4173-83bd-046b10a78b0c)

When the start profile button was pressed, the following errors were displayed in sequence:
![image](https://github.com/user-attachments/assets/8df47291-a4fd-47b7-bd65-2354738875e7)
![image](https://github.com/user-attachments/assets/41253ee0-d371-4470-906c-b9a4a1c316e8)

The profile launched successfully after the second error was acknowledged and the axis were responding as expected.

**Comment by muchimi** [comment]
Confirmed and resolved in m4.9.
