### ISSUE TITLE
JG 13.40.15ex (m4.9) - Response curves with offset center point (0,0) not displayed correctly when profile reopened.

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#148]
This is a re-attack on previously opened issues wrt reponse curves. It was observed on m4.9. I will perform regression testing with .14ex and the legacy JG (non-ex) to try and identify the first occurence.

Symptoms:  Response cuves work as intended but are incorrectly depicted in the UI as a standard linear basic curve.

It appears to be linked to offset center points.

how to currently reproduce:
(1) Create a new profile;
(2) Remap an axis and apply a response curve;
(3) Modify the curve to include an offset of the center position;
(4) Enable the profile and call up the in’ut viewer;
(5) Visualize on the viewer that the curve is correctly applied;
(6) Save the profile (test.xml)
(7) Either close JG or open another profile;
(8) Re-open test.xml

What is happening: the curve created at step (3) is now incorrectly displayed, sometimes as a flat horizontal line, sometimes a standard basic linear curve. However, enabling the profile results in the same response as (4).

this was posted via mobile, i will try and include screenshots and videos later.

**Comment by Lolo401** [comment]
13.40.13ex (h) is the last version where response curves were loaded correctly.  The here-above mentionned procedure was executed on 13.40.13, 13.40.14, and 13.40.15.  The curve was setup like this :

![image](https://github.com/user-attachments/assets/8992dc10-f224-483f-8d32-3046364b160f)

After closing JG and reloading the profile, here are the screenshots for the different versions:

**13.40.13ex (h):**
![image](https://github.com/user-attachments/assets/589de5a9-371a-435e-aa2a-2a2b9ff96360)

**13.40.14ex (m22) and 13.40.15ex (m4.9)**
![image](https://github.com/user-attachments/assets/e99899de-f752-4324-ae4b-02379bf8428c)

**Profile (remove .txt from extension):**
[test2.xml.txt](https://github.com/user-attachments/files/17447018/test2.xml.txt)

Note: The axis is T-Pendular Rudder X Axis.

XML Code:
<container type="basic">
                        <action-set>
                            <vjoyremap vjoy="1" axis="1" mode="VJoyAxis" input="1" axis-type="absolute" axis-scaling="1.0" 
                                     axis_start_value="0.0" range_low="-1.0" range_high="1.0" reverse="False" 
                                     action_id="2341c4183996404a948b397978052116"/>
                            <response-curve action_id="dddea190a5554b71bbd8ab1cf390e113">
                                <mapping type="cubic-spline">
                                    <control-point x="-1.0" y="0.0"/>
                                    <control-point x="1.0" y="1.0"/>
                                </mapping>
                                <deadzone low="-1.0" center-low="0.0" center-high="0.0" high="1.0"/>
                            </response-curve>
                        </action-set>
                    </container>

You can immediately see by the two control points that the curve displayed by .14 and .15 is incorrect.

**Comment by Lolo401** [comment]
Note: 
Interesting finding, probably related, JG Ex .14 and .15 automatically add a control point at (0,0) whereas .13 does not.  When a response curve is created on .13 it gets displayed like this:
![image](https://github.com/user-attachments/assets/6676fbec-d67b-4e9b-9654-0c0f2bbb15a5)

In .14 and .15, it looks like this:
![image](https://github.com/user-attachments/assets/115f5495-164e-4e82-838c-3085dbe489a3)

**Comment by muchimi** [comment]
(1) an extra center point was automatically added regardless of symmetry mode:  I've removed that default behavior.
(2) the curve editor UI was updated to show the current output more visibly, and it's now possible to click a button to delete a control point with a confirmation box if the control point can be deleted.
This updated behavior is in 13.40.15ex m4.10.

**Comment by muchimi** [comment]
Resolved in https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m5_1.zip
