### ISSUE TITLE
Error when pressing save

### ISSUE THREAD

**Issue by Smuli34** [muchimi/JoystickGremlinEx#149]
Maybe some random error when I saved my profile.

![image](https://github.com/user-attachments/assets/d5882a85-542f-4bdd-ab2c-fee2f52633ea)

**Comment by muchimi** [comment]
This is a bug related to logging and was corrected in m4.10.
Good find!

**Comment by muchimi** [comment]
Resolved in https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.15ex_m4/joystick_gremlin_13_40_15_m5_1.zip
