### ISSUE TITLE
Randomly stop and delete Joys and profile.

### ISSUE THREAD

**Issue by Raz0rLegend** [muchimi/JoystickGremlinEx#15]
hi ! 
I hide my joys after i load the profile into JG. But randomly everything stops and my joys are not anymore recognize because of the hiding. After that all my profil disapear, and i need to unhide, shut JG, load the profile, and hide again... Is there a way to force the profile even with any connection or deconection ?!

I need to precise : my XboxControler isn't connected, and i use à Logitech G915 Wireless and a Logitech 502 Wireless sometimes they have a standbye mode. It can be the problem ?!

![image_2024-02-12_213427080](https://github.com/muchimi/JoystickGremlinEx/assets/75459640/5c28afc9-8e1f-40a5-9aa0-08863ec3d371)

EDIT : 
I've go this error at the lauch too.

![image_2024-02-12_213859767](https://github.com/muchimi/JoystickGremlinEx/assets/75459640/8d3322a2-cd2e-4243-9fa6-202d42b32988)

**Comment by muchimi** [comment]
Thanks for reporting.  I'll have to look at the pyside6 error.
I know the directX layer throws all sorts of errors when devices are connecting and disconnecting at runtime - this has been reported in another issue as well.   
This will require some surgery to handle correctly as it's more the code learning to handle disconnections and not blowing up if you send output to that device and it no longer exists, or re-appears later.   That is not what I consider to be a "normal" behavior as the devices are not expected to be randomly appearing or disappearing when the profile is run, but i'll look into that when I can.

**Comment by muchimi** [comment]
Code has been updated to handle errors in any status bar update gracefully rather than crash starting in 13.40.10ex.
The code will also output log information if an error does occur so we can troubleshoot it.

**Comment by muchimi** [comment]
Closing this for now pending new information.
