### ISSUE TITLE
Import Profile Error

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#157]
When importing profile, I get the below error:

![image](https://github.com/user-attachments/assets/cfd6a900-fb18-4840-a7db-9e4a57e0a166)

**Comment by muchimi** [comment]
Resolved in m4 and above.

**Comment by ZK-273** [comment]
Unresolved,  now this error occurs:

![image](https://github.com/user-attachments/assets/676d481b-25eb-4346-9c8c-9ed776eaabb7)

**Comment by muchimi** [comment]
Please zip up the profile you are looking to import so I can trace through the import to see what may be causing the null value when reading the old profile.  Thanks.

**Comment by muchimi** [comment]
I am in process of refactoring the profile import feature because the current base implementation doesn't handle complex profiles well, and that's causing some load issues.
The work in progress includes:
- handle mode parenting for imported modes
- handle invalid mappings, such as, importing a 6 axis map to a device that only has 4
- refresh issue after import/closing the dialog where the imported data only shows after the profile is saved and reloaded

**Comment by muchimi** [comment]
Import refactored to support more complex profiles.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m6.zip

**Comment by ZK-273** [comment]
I could import the profile without error.

I haven't confirmed every single item/bind as that would take forever based on the size of my profile.

I assume your import results window would show any items that weren't successfully imported, to which I saw none in my import attempt.

Residual minor issue:

After I save the imported profile, I can't go to edit modes, as it says I should save the profile (which I already did).
So I had to close and reopen JSGEX in order to be able to edit the modes.

**Comment by ZK-273** [comment]
MERGE AXIS wasn't imported in successfully.

I have a merge axis definition from the current JSG Legacy Profile that wasn't carried over in the Import.

**Comment by ZK-273** [comment]
MODES:
Not all modes imported.  i.e. the EVA mode from the profile I sent you wasn't carried across.

**Comment by ZK-273** [comment]
A multitude of bind definitions didn't carry over from JSG Original Profile to Imported one.

i.e.  Button 10 below doesn't have any information, whereas the legacy does, etc.

Imported Example:
![image](https://github.com/user-attachments/assets/d868eb5e-73e9-43c5-81a9-6dee4d0e464d)

Legacy Example:
![image](https://github.com/user-attachments/assets/e37efcd4-762c-480d-9e2a-69b85b4a247e)

**Comment by ZK-273** [comment]
Action Description not carried over:

Imported Result:
![image](https://github.com/user-attachments/assets/892cf0aa-e417-44fd-9869-9a73973428d1)

Original:
![image](https://github.com/user-attachments/assets/b01d067d-a886-43dc-89b5-853763c442a7)

**Comment by ZK-273** [comment]
Hopefully the above info is useful to help improve the function.  Thanks.

**Comment by muchimi** [comment]
Further improvements were made to import descriptions and blank modes (modes that have no mappings).
EVA mode moved over, as did descriptions.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m7.zip

**Comment by ZK-273** [comment]
...
**Keyboard Mappings Weren't Identified for Import:**
KEYBOARD, doesn't import/identify the binds defined in the xml file.  Pictures attached:  Original JS Gremlin Screenshot, xml file section being imported, resulting import window in JSG EX:

**Original JS Gremlin Keyboard Mapping:**
![image](https://github.com/user-attachments/assets/ee5f13c2-b706-402e-bbb9-9beac9f74448)

**XML File being imported:**
![image](https://github.com/user-attachments/assets/8a458b78-29e7-410e-a4cd-46a9c88200d2)

**JS Gremlin EX Import Screen:**
![image](https://github.com/user-attachments/assets/26799631-824d-4968-8f3b-64e40955204d)

The Star Citizen (Default Mode) didn't carry over to the Keyboard Import section and thus the binds as shown in the above xml file / JS Gremlin pictures weren't identified......

**Comment by ZK-273** [comment]
**### Clicking the '...' Button next to the Keyboard section Causes Error:**

![image](https://github.com/user-attachments/assets/d91c5e62-f480-44a5-8d72-4f985f4e70ee)

**Comment by ZK-273** [comment]
Other more descriptive information was sent to your Discord DM.

**Comment by ZK-273** [comment]
🤔

**Comment by muchimi** [comment]
Some improvements in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

I am not currently able to replicate an automatic import that uses the incorrect number of hats/buttons/axes on the given selected mapping input and that doesn't mean there is no issue, it only means I'm having a hard time duplicating the problem.

**Comment by ZK-273** [comment]
> Some improvements in: https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip
> 
> I am not currently able to replicate an automatic import that uses the incorrect number of hats/buttons/axes on the given selected mapping input and that doesn't mean there is no issue, it only means I'm having a hard time duplicating the problem.

I wonder why the original JS Gremlin doesn't seem to have an issue understanding the mapping from the xml file that we're trying to import into EX?

**Comment by ZK-273** [comment]
Another import error with M32.

Still haven't been able to import anything..

![image](https://github.com/user-attachments/assets/1186a491-769d-4a30-8865-b1dddccdfb09)

**Comment by ZK-273** [comment]
Interestingly (and maybe somehow related to your import function)..

Joystick Gremlin 32 Legacy identifies the lever on the Virpil Alpha Prime as AXIS 6
![image](https://github.com/user-attachments/assets/8d597a65-9917-454a-9d77-2ddc6c00d9a3)

Whereas Joystick Gremlin EX identifies the lever on the Virpil Alpha Prime as AXIS (8) S2
![image](https://github.com/user-attachments/assets/cd096fac-565c-49e8-842f-5986c222a147)


So maybe this is a part of and related to the import of a profile..

**Comment by muchimi** [comment]
More work will need to go into profile imports.  At this point if the existing import feature is not working well, the recommended work around to use all the newer features is to either manually edit the XML file, or leverage the copy/paste feature as able.
Not ideal, but this is just not a priority at this time.
