### ISSUE TITLE
MIDI/OSC/KEYBOARD Tabs cause error upon initial Application Install/operation

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#158]
When clean installing and running the EX 13.40.16ex(m3) version.
This includes erasing all former files under the \Joystick Gremlin Ex folder

When selecting MIDI, OSC and KEYBOARD tabs for the first time:  No Error Occurs.

When moving past and selecting SETTINGS Tab for example, and then going back to choose OSC or MIDI, the following Error(s) occur:

OSC TAB:
![image](https://github.com/user-attachments/assets/572185ba-e2bd-443e-9117-9dd0ffc9999a)

MIDI TAB:
![image](https://github.com/user-attachments/assets/397c45ee-d945-4af5-a976-1915a31b81fc)

KEYBOARD TAB:
![image](https://github.com/user-attachments/assets/fa259220-6397-42c7-b8c2-1c3940ee07b1)

**Comment by ZK-273** [comment]
Resolved

**Comment by ZK-273** [comment]
After importing and enabling/disabling what I guess is the default profile, this error now occurs when pressing the keyboard tab.
Seems maybe related, do reopening

**Comment by ZK-273** [comment]
After importing and enabling/disabling what I guess is the default profile, this error now occurs when pressing the keyboard tab.
Seems maybe related, do reopening:

![image](https://github.com/user-attachments/assets/f33c0fab-1211-4136-9356-4618c20272c8)

**Comment by muchimi** [comment]
The profile import feature has changed.
Please verify if the behavior persists with m6; I am not getting errors on your test profile in m6. However, it may also be the options I selected as import can be quite complex.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m6.zip

**Comment by ZK-273** [comment]
I haven't encountered these errors again, so it might be resolved.
