### ISSUE TITLE
Enhancement: Sound Collections

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#159]
Much like what VoiceAttack has below, would it be possible to include a library of the same or similar sounds we could have access to when wanting to play sounds?
I guess the sounds in VoiceAttack are within a .dat file and not publicly available. (Would be nice if they were)

Any ideas or possibilities surrounding this?

Thanks!

VoiceAttack Screenshot Reference Below:
![image](https://github.com/user-attachments/assets/c647a885-9c82-4cb2-8d34-ebfdae62fa1d)

**Comment by muchimi** [comment]
I'm going to close this for now - I've noted it's one of the asks.  The current method is to just point to a wave file and use the play sound action, then use cut/paste where needed.
There is a challenge in that I am not able to publish copyrighted or licensed sounds with the distribution under the current licensing terms.
