### ISSUE TITLE
Enhancement:  Allow left/right panes of the JSGEX Window to be adjustable in horizontal width

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#160]
Could you please add the ability to adjust the left and right-hand panes' horizontal width based on a vertical delimiter something like below?

Thanks:

![image](https://github.com/user-attachments/assets/ee723007-6e77-4a3f-881e-f18ca2642ef0)

**Comment by muchimi** [comment]
I looked into this a while back, and it's not something QT easily does at the moment, unfortunately.
It is possible with time investment and likely a custom control - I already had to rewrite the slider control from scratch so it doesn't crash QT anymore, so it is completely doable and already on my internal wish list.

I'll keep it as a enhancement request.

**Comment by muchimi** [comment]
I found something that may work - a splitter object.  Investigating.

**Comment by muchimi** [comment]
Feature added in 16 m9
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m9.zip

**Comment by ZK-273** [comment]
> Feature added in 16 m9 https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m9.zip

Thank you.  Seems to be working ok.  I'll keep an eye on it.
