### ISSUE TITLE
Error message by switching off 'Enable MIDI input' and ´Enable OCS input´ in the options menu

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#163]
Hi,
Switching off the 'Enable MIDI input' ends in an error message.

![Screenshot 12_1](https://github.com/user-attachments/assets/95e5f452-5348-471e-9a93-7575b673af13)

Also when switching off the option ´Enable OSC input´

![Screenshot 12_2](https://github.com/user-attachments/assets/f2ba8773-a65b-4ecd-8ed6-96c6e225ddc2)

**Comment by muchimi** [comment]
Thanks for reporting.

**Comment by muchimi** [comment]
Resolved in 16 m11
Was due to a prior hotfix in m6 changing the checks for MIDI and OSC support layers.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m11.zip

**Comment by SyFiD** [comment]
Thank you!
