### ISSUE TITLE
Error by insert ´Merged Axis´ action for an axis

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#164]
An error is issued when 'Merge Axis' action is inserted for an axis.

![Screenshot 12_6](https://github.com/user-attachments/assets/5d1143e8-3ded-44fc-8fac-9eefa4fad74d)

Hier ein Video dazu:
https://github.com/user-attachments/assets/15cfadca-eec9-4024-80cb-e7e372ec1409

**Comment by muchimi** [comment]
Thank you for the video - so the video helped a lot because the issue appears to happen if you do a mapping on the last device (in this case dial 8).  Perfect (for bug fixing that is).

**Comment by muchimi** [comment]
This is resolved in m13.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m13.zip

**Comment by SyFiD** [comment]
It's all right now. It works!
