### ISSUE TITLE
Error by clicking ´Sort Devices´

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#165]
Hello,
I get an error when I call up 'Sort Devices' under Tools. 
In the options, 'Enable MIDI input' is switched off.

https://github.com/user-attachments/assets/7b91c169-2523-4478-abb3-effdb418a0e5

I get a similar error when I have switched it off in the 'OSC MIDI input' options.

https://github.com/user-attachments/assets/a12ffba2-ef08-4952-af44-91a9a16179c3

**Comment by muchimi** [comment]
Indeed - the code was not checking for either option being disabled.  Fixed in m15.

**Comment by SyFiD** [comment]
Thanks! It works now.
