### ISSUE TITLE
Error message in Vjoy Remap when clicking on the spaces or numbers

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#169]
Hallo muchimi,
I get an error message when I click on the numbers between the buttons in 'Vjoy Remap'.
https://github.com/user-attachments/assets/6bf34ede-1422-4c62-b5b5-03ebaa443c8f

**Comment by muchimi** [comment]
Ok thanks.

**Comment by muchimi** [comment]
Resolved in 16 hotfix m17
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m17.zip

**Comment by muchimi** [comment]
Note: this version has been updated for other features.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m18.zip

**Comment by SyFiD** [comment]
The error has been fixed since the M17.
Thank you!
