### ISSUE TITLE
Adding switch position in Switch container generates  a no setter error

### ISSUE THREAD

**Issue by PainfulByte** [muchimi/JoystickGremlinEx#172]
When adding a switch position to the switch container, an error raises about Switch container having no setter:

`2024-11-12 20:32:07      ERROR Uncaught exception:
Traceback (most recent call last):
   File "D:\Games\Tools\joystick_gremlin_13_40_16_m21\_internal\container_plugins\switch\__init__.py", line 415, in _add_position
    self.profile_data.position_count = len(self.profile_data.position_data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: property 'position_count' of 'SwitchContainer' object has no setter`

However, deleting on of the 2 visible switch positions makes the third one appears. So you go from switch position 1 & 2, delete 2, switch positions 1 & 3 are now visible. 

Also, all three switch positions are still visible in the action conditions for the container.

**Comment by muchimi** [comment]
This was an unfortunate editing error on my end not removing a superfluous statement.  Fixed in m22.

**Comment by muchimi** [comment]
There is a sample usage guide / recipe for the switch container in Discord.

**Comment by muchimi** [comment]
Resolved in:

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m22.zip

**Comment by muchimi** [comment]
Please advise if resolved.
Current patch:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by PainfulByte** [comment]
Resolution confirmed.
