### ISSUE TITLE
Problem: the 'Create 1:1 mapping' currently only seems to work with the 'Remap' action

### ISSUE THREAD

**Issue by SyFiD** [muchimi/JoystickGremlinEx#174]
Hello,
the 'Create 1:1 mapping' currently only seems to work with the 'Remap' action. Would it be possible that it also supports 'VJoy Remap'?
Currently, the display of the assignment of the axes and buttons does not seem to work properly for me with the 'Remap' action. Similar to the previous problem #168.
These are only displayed when the axis or button is selected. 
In addition, it lags a lot after executing 'Create 1:1 mapping' with 'Remap'.

**Comment by SyFiD** [comment]
I meant the action in the menu bar.
![grafik](https://github.com/user-attachments/assets/8552b141-1eda-4f9a-beee-f47d5023a4bb)

**Comment by muchimi** [comment]
Resolved in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m22.zip

**Comment by SyFiD** [comment]
Yes, is works now!

**Comment by SyFiD** [comment]
However, I still had a suggestion for a possible later update.
If you have several vJoy devices and you want to assign them with the 'Create 1:1 mapping' function, only vJoy1 is addressed. It would be nice if you could select the vJoy device to be mapped.
This would save you having to change the mapped buttons manually. With 128 buttons + axes it is a bit tedious to change.
It would also be practical, as with buttons or axes, to have a label indicating which vJoy device this assignment refers to. This would give you a better overview of which function is assigned to which vJoy device.

![vJoy_1](https://github.com/user-attachments/assets/20403dbb-3bdd-4328-b755-9bf9812c4982)

Should I post this suggestion in a separate topic?

**Comment by muchimi** [comment]
m23 adds a new configuration dialog for 1:1 mapping to address a few shortcomings.
![image](https://github.com/user-attachments/assets/7ddb34e9-cd2d-4483-8743-d5104cc9ac1c)

**Comment by muchimi** [comment]
Resolved in m23
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m23.zip

**Comment by SyFiD** [comment]
Nice tool! It is working as hoped!
