### ISSUE TITLE
error on a click button

### ISSUE THREAD

**Issue by Miso581204** [muchimi/JoystickGremlinEx#175]
When I click one button on joystick I received this error
![Sans titre](https://github.com/user-attachments/assets/4cfd5273-8499-44a7-ab17-46180e271907)

**Comment by muchimi** [comment]
Thank you - yes this is similar to another error previously reported and is fixed in m23 and introduced in m22 as it fixed the refresh issue - and QT got the better of me with optional arguments.

**Comment by muchimi** [comment]
Resolved in m23 (introduced in m22)
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m23.zip

**Comment by muchimi** [comment]
Please advise if resolved.
Current release:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip

**Comment by muchimi** [comment]
This has been resolved.
