### ISSUE TITLE
JG Ex 13.40.16ex (M23) - Crash at launch, physical devices not detected

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#177]
The following was observed when opening m23:

![image](https://github.com/user-attachments/assets/b444fc3b-9b62-40b1-bbcc-e0f70b93f09b)

Every time JG Ex is opened, a random number of devices are detected after the error is acknowledged.  The two attempts depicted below were done in succession.  Attempt #1, error acknowledged, JG Ex closed, Attempt #2.

(1) Attempt #1:
![image](https://github.com/user-attachments/assets/195ab2d3-61b7-418e-b837-6cafa4a92d73)

(2) Attempt #2:
![image](https://github.com/user-attachments/assets/092285a6-b6c8-4cfa-92f6-1d8e64e23370)

This error is extremely similar to a previous issue: Error related to issue #126 : JG Crashes at launch.

**Comment by Lolo401** [comment]
Note: The problem also manifests itself with m22. 
However, JG Ex launches find with m20.

**Comment by muchimi** [comment]
IIRC, you are using vjoy as input?
I am adding additional checks in the code for missing VJOY IDs (for example, if the number of VJOY devices changed from the last time a profile was saved).  
That will be in m24.

**Comment by Lolo401** [comment]
Yep, I am using one Vjoy as input.

Also, I can't say if it is related or not but after trying m23, my entire Vjoy / JG Setup became corrupt.  Everytime JG Ex would get launched, a new instance of XBox 360 Controller would get created as a device resulting in 6+ Xbox360 controllers in the device manager.  All  my Vjoy GUID's changed.  But the weirdest thing is that VJoy 2.1.9.1 started crashing at start with all devices disabled and showing 32 buttons.  I had to do a complete system restore, boot into safe mode, uninstall Vjoy, manually erase all drivers and reinstall Vjoy.

If I can find a link, I'll post it.

**Comment by muchimi** [comment]
That's ok - the code changes should flag any issues with why it's not finding your input (if that's what's going on).  Hard to tell because I can't tell if it's an initialization bit or truly something missing.  The log will tell us in m24.

**Comment by muchimi** [comment]
Proposed fix:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m24.zip
