### ISSUE TITLE
JG 13.40.16ex (m24) - Clicking on the central control point (0,0) of a response curves modifies the curves and results in crash

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#178]
A video is worth a thousand words :

https://github.com/user-attachments/assets/5faaecd8-06c6-45fd-8a94-20d4d41e4e13

Double clicking on the central node randomly modifies the curves until it crashes JG Ex due to a division by 0.

**Comment by muchimi** [comment]
Ah legacy actions .... Ok I'll take a look.

**Comment by muchimi** [comment]
Does this happen in Response Curve EX?

**Comment by Lolo401** [comment]
Yes Sir but different error messages (in m17) :

![image](https://github.com/user-attachments/assets/0858cd97-35a8-4925-8cb9-4e4ed4d2ec17)

**Comment by Lolo401** [comment]
In m24:

![image](https://github.com/user-attachments/assets/00b978f0-4e1e-4439-b355-228e2385a129)

**Comment by Lolo401** [comment]
It occurs when trying to add a control point at the same position as the central control point.  It is honestly a niche case and would not spend too much time trying to fix it unless it has a ripple effect on something else.

I only discovered this as I use a lot of response curves where the central point is not (0,0)

**Comment by muchimi** [comment]
I have added a check for invalid fit data in the legacy code in m25.
I was able to add a 0,0 central point with no issue so I suspect it's just something in the legacy code that does this and I'll need to dive into it - but the more evident fix is that the fit code should check for bad data...

**Comment by muchimi** [comment]
Please see if this happens in the replacement curve (Map to Curve Ex) - that code is the same that runs the input curve and the curve on Map to Vjoy.

**Comment by muchimi** [comment]
At some point I'll remove all the replaced containers because it's becoming difficult to maintain the old and the new...
Before that, the code will need to auto-convert the containers, a feature I need to add for four actions so far (remap, map to keyboard, map to mouse and the response curve.

**Comment by Lolo401** [comment]
is Map to Curve in M25  ?  I dont see the option in m24....

**Comment by muchimi** [comment]
Sorry, it's called Response Curve Ex, not map to curve.
Identified an issue when duplicated points could cause a fitting error (division by zero).  Curve math now ensures that points are unique.

Proposed fix:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m25.zip

**Comment by muchimi** [comment]
Marking this resolved as the issue has not been reported persisting.
