### ISSUE TITLE
JG 13.40.16ex (m24) - Inconsistent Device Detection

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#179]
Here is a screenshot of m24 (top) and m17 (bottom) running at the same time:

![image](https://github.com/user-attachments/assets/69e54f4d-deb3-4ec5-990e-469b49040c12)

Everytime m24 is launched, some devices are not being recognized.

It appears that at some point after m17, an update resulted in incoherent and erratic device ID handling.  

It is pretty hard to reproduce, results appear to be random.  However, it always seems to occur after JG Ex has be relaunched at least once.  After a reboot, the first launch of JG EX m24 is working as per design.  However, after closing and reopening JG Ex, those issues appear.

Is there any log file or anything I can record or publish to help identify the issue ?

Cheers.

**Comment by muchimi** [comment]
Yes, the log file would be helpful.  Does this happen when you are NOT using vjoy devices as inputs?
The error you had earlier had to do with a missing vjoy ID.
The log file is found at %userprofile%\Joystick Gremlin Ex\system.log
GremlinEx should be in verbose mode first.
It will list all discovered inputs and outputs in the initialization phase.

I'll test on my end with a test input vjoy (all, as always, runs fine over here lol).

**Comment by muchimi** [comment]
And yes, it works like a champ over here with a vjoy input.  Never a dull moment!
![image](https://github.com/user-attachments/assets/701270a1-d3ff-4d03-835a-6feee75de179)

**Comment by Lolo401** [comment]
I d like to confirm the test conditions:

I am using VJoy 2.1.8.1 and HidHie 1.5.230.0.  Is that what you are using as well ?

**Comment by muchimi** [comment]
Rolled up into:
https://github.com/muchimi/JoystickGremlinEx/issues/189
