### ISSUE TITLE
Question: Looking to add a new action plugin, publish on a fork or create a PR?

### ISSUE THREAD

**Issue by jc43081** [muchimi/JoystickGremlinEx#18]
I am writing a new action plugin (couldn’t use the plugin feature) and since you have a more recent version (plus lots of new features), I used your version as my starting point. As I near finalizing it, I am wondering if you would prefer me to publish a separate version on my fork or merge my changes with a PR. My changes are mostly within the new action plugin, but a few changes were made to the base code (and I fixed a few bugs).

My only concern going the PR route is I may have a potential flurry of PRs for fixes and I didn’t know how much you wanted to be bothered going forward. You can check out my changes in more details if you want by visiting my fork and the “star citizen” branch. Let me know your thoughts as I could go either way.

Thanks for continuing to extend JG. It is a great tool!

**Comment by muchimi** [comment]
I like bug fixes!  Perhaps we can start with the core bug fixes I can incorporate those and you can publish the plugin separately?
I'll take a look at your changes.  Actions is one of the areas I haven't looked much into outside of vjoyremap (and that has a few bugs too).

**Comment by muchimi** [comment]
I pushed your coderunner start() change to tag [13.40.7x RC).  Please check and I'll publish a release if all looks ok.

https://github.com/muchimi/JoystickGremlinEx/commit/bec42b8735f7017ba21826a4a82caa2e05f3fecb

**Comment by jc43081** [comment]
TBH, I don't remember making a change to coderunner. The fix I was referring to I had only committed locally, but have now pushed it up. It was an error when changing modes on the Keyboard tab. https://github.com/muchimi/JoystickGremlinEx/commit/c7f4361c62147642d8252d2773c9177e674363c9

Just to clarify, the changes are made go beyond the plugin framework. It is similar to your vJoyRemap action. So when you mention "publish the plugin separately", what do you mean? I would be glad to connect on Discord if that is easier to talk through this.

**Comment by muchimi** [comment]
Give me your discord - I'm at @muchimi.  Glad to have a chat.

**Comment by muchimi** [comment]
We are working on a solution offline.
