### ISSUE TITLE
dead zone button presets not working on output curves

### ISSUE THREAD

**Issue by ktall** [muchimi/JoystickGremlinEx#181]
well everything is in the title. 
If you set deadzones with the sliders, no problem. If you clic a preset button (like 'center 10%' ) the dead zone is not applyied
Version used M26

**Comment by muchimi** [comment]
Thanks for reporting.  Solution inbound.

**Comment by muchimi** [comment]
Resolved in 16m27
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m27.zip
