### ISSUE TITLE
Button grid show/hide

### ISSUE THREAD

**Issue by ktall** [muchimi/JoystickGremlinEx#184]
Button grid show/hide is available only for press and release.
I think the checkbox should be link to the grid so it's available each time the grid is shown

exemple : 

1. do a vjoy remap for a button
2.  set the mode to Pulse

=> no 'show grid' check box

for as good as the grid is while setup, the view can be very big very quickly

**Comment by ktall** [comment]
Maybe a global 'show grids' in the main 'tools' tab too so we can quickly swap between nice setup and nice readability

**Comment by muchimi** [comment]
You can do that already if you hold the control key and click the checkbox - it's a global setting to enable/disable.  It keeps track of it that way, and yes, could be part of the options as well, easy enough to do.

**Comment by muchimi** [comment]
The grid is visible for any option that has a button tied to it.  The grid is visible for:
- button press
- button release
- axis to buttons
- toggle button
- pulse button

Was there an option that is button releated that didn't show the button grid when expecting one?

**Comment by daganael** [comment]
no the issue is if you setup a toggle or a pulse for instance, the 'show grid' checkbox is not present

**Comment by muchimi** [comment]
So you're missing this option, not the grid?
![image](https://github.com/user-attachments/assets/6c717484-2c5e-4708-982d-f67fcdb63a75)

**Comment by muchimi** [comment]
> It's nice and working well but not clear if you're not here to tell us :P I would still argue that a global checkbox in menu would be more user-friendly (even though, once known, the ctrl clic is really handy)

That was actually in the patch notes :P

**Comment by daganael** [comment]
> So you're missing this option, not the grid? !

Yes

**Comment by daganael** [comment]
> > It's nice and working well but not clear if you're not here to tell us :P I would still argue that a global checkbox in menu would be more user-friendly (even though, once known, the ctrl clic is really handy)
> 
> That was actually in the patch notes :P

Sorry, you're too fast. I didn't see you already posted an update

**Comment by muchimi** [comment]
I added the display of the missing row in the axis to button mode (that should display in any button mode).
Axis to button is weird because it's an axis inpuyt and it's not expecting to put out buttons - just not something it wants to naturally do so it has to be coerced.

**Comment by muchimi** [comment]
Also, the tooltip has the instructions on how that checkbox behaves...
I'll add a repeater checkbox to config just in case.

**Comment by muchimi** [comment]
The only reason these comments exist is so you can be reminded that there was, in fact, a futile attempt made to explain the feature...  MOTDs, like manuals, should indeed be ignored as good software should just flow and be intuitive.  I do agree with that.

**Comment by daganael** [comment]
that's a very deep rabbit hole as what flow and is intuitive is mostly cutural and hence vatsly different from one person to one other.... but I agree with the intention

**Comment by muchimi** [comment]
Proposed fix in m28
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m28.zip

**Comment by daganael** [comment]
I think you missmatched two tickets here you fixed the checkbox for the axis to button (i'll comment there too) but the checkbox is still missing for the other button modes (toggle, pulse, etc)

![{88F462C5-B753-4487-8228-399B7393A5F1}](https://github.com/user-attachments/assets/15727a2b-ff8f-4b07-b407-ebd763196e95)

**Comment by muchimi** [comment]
Proposed fix in m29 for the other modes in when mapped to a button (yes, I completely missed the distinction between the two tickets).
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m29.zip
