### ISSUE TITLE
Axis to button modes

### ISSUE THREAD

**Issue by ktall** [muchimi/JoystickGremlinEx#185]
When you setup an axis to button, you don't have button mode
I think the full button object should be inserted here instead of a default 'press'
(that would include the 'show grid' from the previous ticket)

**Comment by muchimi** [comment]
You do not see something like this when in axis to button mode?
![image](https://github.com/user-attachments/assets/3b15eff8-ef8c-4f20-8e73-eb9f297ed8cb)

**Comment by daganael** [comment]
sorry I wasn't clear.
I see exactly that, meaning I can't change the mode of the button. can't set a released mode, can't set a toggle mode, etc like we have for button remap

![{CCD4D67B-2CBA-4F5D-931F-38643E9DDB76}](https://github.com/user-attachments/assets/58cdff67-3315-4dc8-82fa-3fc69823bee8)

![{5FCBB92F-D682-48A3-BAFE-B955D6751E48}](https://github.com/user-attachments/assets/446634f4-a13c-4953-8a39-df8d67834d50)

on axis to button it's 'press button', no options 
![{7A96214D-23D8-4C6D-ADDC-B59C5A737FAE}](https://github.com/user-attachments/assets/fe374304-a75a-4b6d-8fc0-08945ce24f94)

**Comment by muchimi** [comment]
Proposed fix in m28
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m28.zip

**Comment by daganael** [comment]
Here I think is the ticket you missmatched the grid checkbox issue with.
here the question is : can you add the other button modes (toggle, pulse) to the 'axis to button' remap  like I descibed on my previous comment

> **meaning I can't change the mode of the button. can't set a released mode, can't set a toggle mode, etc like we have for button remap**
> 
> ![{CCD4D67B-2CBA-4F5D-931F-38643E9DDB76}](https://private-user-images.githubusercontent.com/36364791/387273202-58cdff67-3315-4dc8-82fa-3fc69823bee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NzU4NTIsIm5iZiI6MTczMTk3NTU1MiwicGF0aCI6Ii8zNjM2NDc5MS8zODcyNzMyMDItNThjZGZmNjctMzMxNS00ZGM4LTgyZmEtM2ZjNjk4MjNiZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAwMTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YmQ3NTE0YTkzYWE4ZDEzZmYxMDk4ZTVhOWI1NzJiMjdmYWRmZjJmYmFlZWM5OGJjNjhkNzM5YWQ0ZDFmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2cGLbU25DXke9DUT6P_47yzvCbAOSpTuAD5-D-bztVc)
> 
> ![{5FCBB92F-D682-48A3-BAFE-B955D6751E48}](https://private-user-images.githubusercontent.com/36364791/387273250-446634f4-a13c-4953-8a39-df8d67834d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NzU4NTIsIm5iZiI6MTczMTk3NTU1MiwicGF0aCI6Ii8zNjM2NDc5MS8zODcyNzMyNTAtNDQ2NjM0ZjQtYTEzYy00OTUzLThhMzktZGY4ZDY3ODM0ZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAwMTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzEwNDU2MGI5YjlmZTRlODE3ZjBmZmE0Nzc4NGE2MjM0MTEwNjgyNWIyMDg0Mjg3ODdjNDcyYjQ2MDAyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4rGNQjCtPO2s_vx0C_7UTGbQYPwYVkaFxGo7PveZgjY)
> 
> on axis to button it's 'press button', no options ![{7A96214D-23D8-4C6D-ADDC-B59C5A737FAE}](https://private-user-images.githubusercontent.com/36364791/387273535-fe374304-a75a-4b6d-8fc0-08945ce24f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NzU4NTIsIm5iZiI6MTczMTk3NTU1MiwicGF0aCI6Ii8zNjM2NDc5MS8zODcyNzM1MzUtZmUzNzQzMDQtYTc1YS00YjZkLThmYzAtMDg5NDVjZTI0Zjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAwMTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MmUzZWQ1Y2I4MjYzMDRhYWQyODNhZWUxNmU3NGU3Mzc4MzZkZjVmYmFjOTE4YjkzNDNlMTBmOGM2MjU1YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-pmQKNSUHrl-KsTXN-w0wN5Ue3d40WMYZuS_Faav2z4)

**Comment by muchimi** [comment]
Indeed.
Both are resolved in m29.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m29.zip
