### ISSUE TITLE
more dead zone issue

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#187]
hoy,
on the dead zone issue for the default output curve, the buttons are now working. however we have the same issue with the numerical input bellow : value set here are not applied

plus if you set a value for the mid-low input (the center minus, second box) it actually invert the whole curve

**Comment by muchimi** [comment]
I am working on a fix for this, which cascaded into rewriting half of the deadzone logic...

**Comment by muchimi** [comment]
Proposed fix in m28
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m28.zip
