### ISSUE TITLE
m28 : default output curves not loading

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#190]
Sorry, another one.
With m28 the default Output Curves inside the Vjoy Remap on axis is not loaded (not saved ?)  when JG starts

**Comment by muchimi** [comment]
That is likely due to the fact it was saving the old curve data before... Let me take a look at the loading logic.

**Comment by muchimi** [comment]
And indeed, it was.  The fix is in m29.  The tag changed but the load code didn't account for the tag change.

**Comment by daganael** [comment]
perfect
