### ISSUE TITLE
m28 : ouput curves presets don't set dead zones

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#191]
all in the title.
if you save a preset for an output curve like so (see crazy dead zones)
![{84CA9EC9-EDBD-457E-8AC4-7819B2A8D702}](https://github.com/user-attachments/assets/6a10cfe6-6872-4a67-abc1-75f3a9db259e)

when you load it on a fresh curve, you get (no dead zones) : 
![{2AF7ED6D-865A-4D25-BB80-0DABEB7D7B13}](https://github.com/user-attachments/assets/ee20f41a-43a6-4002-a70d-bebd8b891a98)

**Comment by muchimi** [comment]
IIRC, the preset resets the curve shape, not the deadzone.  It's why there's a reset button for the deadzone.
I guess the question is should they be linked?

**Comment by muchimi** [comment]
Now when you save a preset, it does save the deadzone data with it (or should).  I'll double check, haven't looked at this in at least a week so I forget!

**Comment by ktall** [comment]
> Now when you save a preset, it does save the deadzone data with it (or should). I'll double check, haven't looked at this in at least a week so I forget!

If you save the data, then maybe an option on load ?

**Comment by ktall** [comment]
I undrestand your logic here and I recon it's already quite cramped in this view but I would try to keep your logic as it is and do a 'copy/paste curve/paste all' to accomodate more cases

**Comment by muchimi** [comment]
The copy/paste copies all data in the action, including the deadzones.
There was a problem this week with the curve data in map to vjoy that caused it to ignore the data on reload (the serialization for profile and clipboard functions are the same so impacted both loading data from a profile or pasting the data) and the curve data didn't make it over.  Fixed yesterday.

**Comment by daganael** [comment]
was talking about the copy/paste _inside_ the output curve. as it's not a container we can't copy paste the block and so can;t apply curve and dead zones.
the use case is setting up a brand new setup where I want all my axis to get a basic behavior 'slight smooth around 0 and small dead zone' as a baseline.
my way of thinking if : If I need to the exact same more than twice in a row, I should prolly be able to paste it.

SO another way of doing that - maybe easily - would be to remove the text on the clear curve button and to add a copy and a paste button (icons only) next to it.
That way it would just behave as a container
