### ISSUE TITLE
Tempo/Ex & Double Tap are not working with HAT

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#193]
Adding Tempo/TempoEz or Double Tap to the HAT is not working. No output is generated.
I also noticed that Chain is partially working with Hat; only the first action will work, and the second one is not working.

**Comment by muchimi** [comment]
Ok thanks for reporting.  What configuration hat is your hardware using - buttons or continuous?

**Comment by mnf1980** [comment]
I'm using Thrustmaster Warthog POV HAT (both Joystick and Throttle), with vJoy as continuous.

**Comment by muchimi** [comment]
Resolved in m33.
Turns out many legacy containers didn't have any support for hats.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m33.zip

**Comment by muchimi** [comment]
The related issue was reported resolved so I am closing this.  We can re-open if the problem persists.
