### ISSUE TITLE
Vjoy Remap shows HATs up to 128 and generate error

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#194]
Adding "Vjoy Remap" to HAT will show in the output (HAT from 1 to 128). vJoy has a maximum of 4 HATs. Choosing any HAT number above 4 in the output will generate two errors.
I also noticed that the legacy "Remap" has the option to choose a HAT from 1 to 4 & Buttons from 1 to 128 (as per the vJoy configuration), with an extra tab (Virtual button) to select the HAT position, which is not available in Vjoy Remap.
This will force us to choose the legacy "Remap" when adding the "Hat Button" to HAT, as there is no option to choose buttons in the "Vjoy Remap."

One workaround I found is to set up a "Vjoy Remap" in a button and then copy it to the HAT. Doing so will change the output from Button to HAT with the same number, and it will work even when it shows HAT rather than Button. see pic 2

The errors are:
1)
Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\input_item.py", line 1199, in _icon_changed_cb
   File "gremlin\ui\input_item.py", line 1405, in create_action_icons
   File "gremlin\ui\ui_common.py", line 3744, in __init__
   File "D:\joystick_gremlin_13_40_16_m29\_internal\action_plugins\map_to_vjoy\__init__.py", line 2444, in icon
    if os.path.isfile(icon_file):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: _path_isfile: path should be string, bytes, os.PathLike or integer, not NoneType

2)
Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\ui_common.py", line 3766, in _icon_change
   File "D:\joystick_gremlin_13_40_16_m29\_internal\action_plugins\map_to_vjoy\__init__.py", line 2444, in icon
    if os.path.isfile(icon_file):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: _path_isfile: path should be string, bytes, os.PathLike or integer, not NoneType

![image](https://github.com/user-attachments/assets/2c871b4e-0dbc-4f34-9d22-f7051bd7357c)

![image](https://github.com/user-attachments/assets/3cfc0a6e-e191-4b47-a638-3a86a61666f9)

**Comment by muchimi** [comment]
Curious - what does the log file say the vjoy device should have?  128 is buttons - clearly it's confused and thinks the hats are buttons, but I want to verify that the detection shows only the 4 hats for your device.  I'll dive into it.

**Comment by mnf1980** [comment]
VJoy 8/128/4 (1) Axis count: 8 Button count: 128 Hat count: 4

**Comment by muchimi** [comment]
Resolved in m31

**Comment by muchimi** [comment]
This has been verified as resolved in m31/m32.
