### ISSUE TITLE
Diagonal symmetry issue

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#195]
Diagonal symmetry doesn't apply to the zero point (central one) in output curves unless 'force smooth curves' is applied (unchecked and rechecked).
does the UI read the wrong checkbox ?

![{8A8BD7C6-1DB1-4199-AFF8-6024F1E03D1E}](https://github.com/user-attachments/assets/1d9615ab-c1ec-4f85-a10f-8a8458443187)

**Comment by muchimi** [comment]
Possible.  I'll look into it.  I have not come across this yet; however, there was a logic change to account for duplicate points that were creating a "fit" error and the point reference system changed - this may impact the mirror logic...

**Comment by muchimi** [comment]
Resolved in m33

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m33.zip

**Comment by daganael** [comment]
yep, works fine
