### ISSUE TITLE
Conditions Action/Container is not recognizing HATs inputs

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#196]
It seems that the Action/Container does not recognize the input from HATs.
For example, the app does not recognize the HATs input when setting "Joystick Condition" or "vJoy Condition" in Action/Container.

![image](https://github.com/user-attachments/assets/e3a7544c-b7ac-4a22-9cec-63d990af0d33)

**Comment by muchimi** [comment]
Resolved in m31 for Tempo and TempoEx - hat inputs behave different for press/release as they are tied to position.

**Comment by muchimi** [comment]
Resolved in m31/m32
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m32.zip

**Comment by mnf1980** [comment]
working fine with m33.

**Comment by mnf1980** [comment]
I am experiencing a similar issue with the M40; this time, the app is not recognizing the Vjoy HAT position.

**Comment by muchimi** [comment]
Using VJOY as input?

**Comment by mnf1980** [comment]
The container conditions are not activating when using the vJoy HAT.

![image](https://github.com/user-attachments/assets/3d627a42-eb6f-406a-9c36-874ec2843c6d)

**Comment by muchimi** [comment]
This should be resolved at this point but please see if the problem persists in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m47.zip

**Comment by muchimi** [comment]
Assuming the fix worked given no further feedback.  We can re-open if needed.
The most current version at the time this is closed is:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
