### ISSUE TITLE
Green Condition tab even if it has no actions

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#197]
I'm not sure if it is a bug or a feature:
The green dot in the Condition tab is highlighted for the first container if the second container has conditions.
It is also the same if the first container has actions and the second container has none.

![image](https://github.com/user-attachments/assets/bf49ec08-c11b-4cb9-8e5f-aef691915d7c)

**Comment by muchimi** [comment]
More research shall go into this.  Conditions will be the end of me I swear :)

**Comment by mnf1980** [comment]
I really appreciate your work. This app is excellent, and I'm switching from TARGET to this one now. I've been using TARGET for over five years, and it has been outstanding, but more and more controllers (especially from other vendors) have forced me to look for different solutions, and this one is my go-to now. It has a lot of features, and I've been testing it extensively for the past five days.
I've almost shifted 90% of my settings from TARGET to this app, and I'm still figuring out how to do double tap and long tap at the same time.

**Comment by ZK-273** [comment]
I can attest that this also happens to me.  There's a green color for a condition, even though there's no condition set up for the action.

**Comment by muchimi** [comment]
Resolved in m37.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m38.zip

**Comment by ZK-273** [comment]
I've looked at this in my own profile and **can't confirm a fix.**  This is in version m40

Has Conditions:
![image](https://github.com/user-attachments/assets/d03e6c3a-4444-4d8a-bfb4-78b8b743e74d)

Has no conditions, but green dot shows activated:
![image](https://github.com/user-attachments/assets/62412ce3-d6fb-43e1-a644-e70ada828d3e)

**Comment by muchimi** [comment]
More work went into conditions in the last few releases.
This is a thorny subject with the current condition wiring and this is not a breaking feature.
I'm am aware more work needs to go into this when time and priorities permit.
The most current version at the time this is closed is:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
