### ISSUE TITLE
"Axis Value" return to zero after activating/deactivating the GremlinEx

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#199]
After activating/deactivating the GremlinEx, the "Axis Value" returns to "0.000," while the previous value remains.

In the picture below, the value is 0.7, but it is showing as 0 (after deactivating the GremlinEx). Activating the app again and pressing the button set the axis value to 0.7.

![image](https://github.com/user-attachments/assets/bf1c5902-1ac0-415d-8bd0-39749ee427e6)

**Comment by muchimi** [comment]
Resolved in m31
