### ISSUE TITLE
Problem playing sound

### ISSUE THREAD

**Issue by guimoal** [muchimi/JoystickGremlinEx#20]
I'm creating a new profile again with JoystickGremlinEX, but when I set up a PlaySound, when I run it I get an error screen that I attach. Thanks.
![JoystickGremlinEx Fallo PlaySound](https://github.com/muchimi/JoystickGremlinEx/assets/10798433/f0263204-ceb6-4806-91d2-b5131e872142)

**Comment by muchimi** [comment]
Bug fix in https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.7ex
