### ISSUE TITLE
"Axis to Button" generate the last keypress if the output has the same button

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#200]
Setting two (or more) "Axis to Buttons" with the same output button and range split will only output the last button press. This does not happen if the output buttons are different.

In the example below, a double press of the button 128 should happen while moving the slider.
![image](https://github.com/user-attachments/assets/34a880bc-cf4d-459a-b1eb-ab89a1351bb0)

**Comment by muchimi** [comment]
Thanks for reporting.
Also: look into Gated Axis as a workaround for now.

**Comment by muchimi** [comment]
I researched this and did not see an issue with identical mappings, as the data is not shared between action instances.
However, I made a small change in processing logic that should resolve the trigger not happening when it should or spamming.
This will be in m33.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m33.zip

**Comment by mnf1980** [comment]
It is working fine with 33. thanks again.
