### ISSUE TITLE
M31: "Hat to Button" option to release the key when changing HAT direction

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#202]
Thanks for adding this feature.
Could you add an option to release the keys when pushing the HAT in another direction?
In the picture below, I keep pressing the HAT in one position and then keep pressing in the other direction. As you can see, all the buttons are now pressed, and they will only be released if I release the HAT.
A release key may be suitable when changing the HAT direction.

![image](https://github.com/user-attachments/assets/61be1de7-791d-4b12-926c-e563d439dbde)

**Comment by muchimi** [comment]
I will look into this.  One way is to use the pulse option or to return to the center.  As implemented, it's the "sticky" behavior as you've observed.

**Comment by muchimi** [comment]
Feature added in m33.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m33.zip

**Comment by mnf1980** [comment]
Working fine in 33. thanks
