### ISSUE TITLE
M31: Tempo/EX are not working

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#203]
No output when using Tempo/EX. It is working fine on previous builds.

**Comment by muchimi** [comment]
I believe this is resolved in M32 (there was a typo in m31)
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m32.zip

**Comment by mnf1980** [comment]
Solved in 33. thank you
