### ISSUE TITLE
m32 : axis remap set to work on conditions are off 

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#204]
All my remaps done with conditions stoped working in m31/32 versions.
worked fine in m30 and below

can you give us back a dl for m30 ? 
m31 and m32 are not usable for me as it is

**Comment by daganael** [comment]
unpon more testing it seems to work fine on a new profile.
redoing all my conditions in my SC profile and keeping you updated

**Comment by muchimi** [comment]
M33 is around the corner.  I'll keep the last few versions on the download link just in case.

**Comment by daganael** [comment]
ok so after invertigating a bit, it seems that everytime a condition is False the entire bloc stop working

here's an exemple :
![{BF811580-8E22-458E-88D3-9C941BA7874B}](https://github.com/user-attachments/assets/76de5be1-f4cd-44cb-8a7b-3bab6a3655d4)

![{673E1CA3-4E33-4D2D-9BF5-1661A9F73F03}](https://github.com/user-attachments/assets/6ae30722-5d90-4eb1-b8b6-8362e480985b)


when the button is press, the entire container stop working

my normal conditions  for that container are :
![{BF1AC3C8-DEA9-4715-8E7F-0CA3D44CDEC1}](https://github.com/user-attachments/assets/a049be99-ee9a-4c71-808e-2c33cb03077e)

so it never works

was fine in m30 and below

**Comment by daganael** [comment]
seems like action condition's are applied to the container and not to the action

**Comment by daganael** [comment]
vorks fine in m34
