### ISSUE TITLE
Question: what the "Paired Group Member" do

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#205]
I need help finding what this checkbox does. Would you please explain it?

![image](https://github.com/user-attachments/assets/8670c940-e2e1-4008-99be-0a6ad9e2a14f)

**Comment by muchimi** [comment]
Paired buttons send a network trigger to remote clients even when remote control is not enabled.
This is a way to keep buttons synchronized between multiple instances regardless of remote control state.
Hope this helps!

**Comment by mnf1980** [comment]
thanks
