### ISSUE TITLE
OPTIONS > PROFILES > Process Mapping:  Force Numlock Checkbox doesn't allow state change/save

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#207]
When adding a profile mapping in the Options > Profiles > Process/Profile Map Section.
If you select the 'Force Numlock Off' checkbox and save, you can no longer return and uncheck this box and re-save the profile and have it remembered.

![image](https://github.com/user-attachments/assets/4b477f55-8f76-4907-af6e-e9164bf8cf8c)

**Comment by muchimi** [comment]
Force num lock is a per-profile setting and not global.  I wanted to verify you saved the profile and it didn't save the setting?
Let me look at making this a global setting as well.

**Comment by ZK-273** [comment]
> Force num lock is a per-profile setting and not global. I wanted to verify you saved the profile and it didn't save the setting? Let me look at making this a global setting as well.

It didn't save.  Plus checked the xml file as well and didn't save.  Unchecked it, hit close, hit save profile.  Didn't save.  Reloaded the profile after all the above and still was checked.

I'm not sure how it'll work or not work with the other issue I reported about extended scan codes etc

**Comment by muchimi** [comment]
I added a global numlock setting to override individual profile settings.

**Comment by ZK-273** [comment]
I guess my expected outcome was:

1. Ability to save a profile with the 'Force Num Lock' unchecked (per profile)
2. Ability to edit a profiles' 'Force Num Lock'
3. Have the setting be saved on close of the Options/Profile Window
4. Have the correct setting be visually shown in the window for each profile.

Please let me know when there's a new build out with any modifications and I'll test.  Thanks!

**Comment by ZK-273** [comment]
Upon further look, it seems that if this is set in the Gear Icon (next to Modes) in the application, it will prevent the edit/change of those values in the Profile Window.

![image](https://github.com/user-attachments/assets/6b51c3e1-59a3-4276-94df-997dfa008909)


![image](https://github.com/user-attachments/assets/bd1272eb-3264-485e-a693-4cc2c3dcfa67)

**Comment by muchimi** [comment]
Reviewing the logic, I'm going to remove that checkbox because it makes little sense to have it there.  Presumably if a profile numlock state needs to be set, it can be set either in the profile config window, or the global setting, not yet a third setting to override the first two.

**Comment by muchimi** [comment]
Removed option as it didn't make any sense to have a duplicate, separate option here.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m38.zip

**Comment by ZK-273** [comment]
Seems as you removed the Checkbox for the PROFILES section and not the one listed below:

![image](https://github.com/user-attachments/assets/9db54ad2-38fa-4ccc-8bec-99b44265be3d)

I suppose the above is to allow each mode to have a specified state for the Numlock?

So you're ok with the user specifying the Numlock state based on the MODE of the profile?

It seems to me that the state of the Numlock on the 'Profile Level' should be controlled per profile in the Options / Profile Mapping window and now in the Mode Gearbox Window.

Maybe reversed?


![image](https://github.com/user-attachments/assets/428acf3b-de4c-4f92-b113-5fce43f7a778)

**Comment by ZK-273** [comment]
Perhaps there'd be some value to specify 'Per Mode' the state of the Numlock when entering a mode?

Or, perhaps put that option in the Switch Mode / Temporary Mode Switch  actions instead?

**Comment by muchimi** [comment]
Closing per request.
