### ISSUE TITLE
JG 13.40.16ex (m37): Input response curves and deadzones saved but not loaded

### ISSUE THREAD

**Issue by dsedivec** [muchimi/JoystickGremlinEx#210]
Tested with m31 and m37, same behavior.

Steps to reproduce:

1. New profile
2. Make a 1:1 remap between any joystick axis and any Vjoy axis using the Vjoy Remap plug-in (without this, input curve doesn't seem to be saved)
3. Click the joystick axis input curve editor
4. Use presets Bezier 4 and deadzone center 2%
5. Save the profile to test.xml
6. Load the profile

Expected result: Input curve and deadzone are set on the axis where I set it
Actual result: Input curve and deadzone are reset to default on that axis

Note that I _can_ see the `<response-curve>` element with my settings (control points, `<deadzone ...>`) in the profile XML, as a child of the `<axis>` tag.

Thank you for this software, it's essential and there's nothing else like it :)

**Comment by muchimi** [comment]
Thanks for the kind words and for reporting.
I had missed the data tag change when the new curve editor became the default.  The other issue was the icon indicated a curve exists on the axis was also not updated correctly as a result.
Both fixed in the next patch (m38).

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m38.zip

**Comment by dsedivec** [comment]
Confirmed fixed, thank you again :)
