### ISSUE TITLE
(M37) [STATUS] Does not change to 'Running' when switching to game window

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#211]
With the below profile set up, when the game is changed to focus, the profile should switch to a status of 'RUNNING'.
However, this doesn't happen.

I have to manually press the gamepad controller icon to get the profile running first and then switch to the game. (Star Citizen / Borderless).

JS Gremlin is being run as Administrator

Here are the settings:

![image](https://github.com/user-attachments/assets/c48345fd-8759-4b02-8660-a1f9dc62dcea)

![image](https://github.com/user-attachments/assets/6201833e-1dc6-4472-9382-11056db43e41)

![image](https://github.com/user-attachments/assets/8309a52d-4589-433d-a836-8df32e0504ef)

**Comment by muchimi** [comment]
This is related to other issues reported since this was reported, and resolved or at least improved.
We can consolidate all the profile/process mapping items to a single issue.
