### ISSUE TITLE
(M37) Adding Conditions Generates Error when using dropdown device box

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#212]
When adding conditions to a container's actions, if I choose other devices (besides Joystick Condition), this generates an error.

![image](https://github.com/user-attachments/assets/acc2c460-704f-483e-8062-d03dccabe209)

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m38.zip

**Comment by ZK-273** [comment]
Confirmed.  Seems to be OK now.

**Comment by ZK-273** [comment]
ok

**Comment by ZK-273** [comment]
Confirmed. Seems to be OK now.
