### ISSUE TITLE
From 13.40.16 (m28) to at least 13.40.16 (m36) Joystick Gremlin Ex fails to load or import Joystick Gremlin v13.3 profiles

### ISSUE THREAD

**Issue by Tsudico** [muchimi/JoystickGremlinEx#214]
I've tried in every version available since m28 and the profile doesn't load.

Log file shows the following when trying to load a profile from Joystick Gremlin v13.3:
````
2024-11-27 10:11:27    WARNING Outdated profile, converting
2024-11-27 10:11:27      ERROR Invalid profile content:
9
Traceback (most recent call last):
  File "joystick_gremlin.py", line 2427, in _do_load_profile
  File "gremlin\base_profile.py", line 2157, in from_xml
  File "gremlin\profile.py", line 125, in convert_profile
KeyError: 9
````
Looking at line 125 in `gremlin\profile.py`:
https://github.com/muchimi/JoystickGremlinEx/blob/7f987d06ecd4681e5ba2622a2031e6701ac1ca4e/gremlin/profile.py#L125

The trouble appears to be that Joystick Gremlin v13.3 actually creates `<profile version="9">`, whereas the import only expects up to version 8:
https://github.com/muchimi/JoystickGremlinEx/blob/7f987d06ecd4681e5ba2622a2031e6701ac1ca4e/gremlin/profile.py#L106-L115

The develop branch of Joystick Gremlin further advances the version from profile version 9 to profile version 14 in commit `0bc7c28`.

I've included the profile I am attempting to load.
[Star Citizen Dual Alphas - Shifted Southpaw.zip](https://github.com/user-attachments/files/17937235/Star.Citizen.Dual.Alphas.-.Shifted.Southpaw.zip)

**Comment by Tsudico** [comment]
Looking a little further into it, the converter sets the current version to 10 instead of 9 on line 60:
https://github.com/muchimi/JoystickGremlinEx/blob/7f987d06ecd4681e5ba2622a2031e6701ac1ca4e/gremlin/profile.py#L60
So when it compares the versions on line 123, version 9 is the only one that passes the condition while not having a conversion in the map:
https://github.com/muchimi/JoystickGremlinEx/blob/7f987d06ecd4681e5ba2622a2031e6701ac1ca4e/gremlin/profile.py#L123-L125

**Comment by muchimi** [comment]
Thank you for reporting and all the details.
Resolved in the next patch.

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m38.zip

**Comment by Tsudico** [comment]
Verified fixed in m38
