### ISSUE TITLE
13.0.16ex (m40) Map to Keyboard Ex always shows a plus sign for Current key combination which may be confusing when using + key

### ISSUE THREAD

**Issue by Tsudico** [muchimi/JoystickGremlinEx#215]
Map to Keyboard automatically includes a + sign when it shows the current key combination:
![2024-11-28 Map2Keyboard+](https://github.com/user-attachments/assets/5c15b1db-c12b-43db-b373-d63ca4726a80)

This confused me at first, as I thought it was indicating a default key was selected.

When I then chose a key, it made me wonder if I was going to get both the key I selected and a + as well.
![2024-11-28 Map2Keyboard+Numpad+](https://github.com/user-attachments/assets/1153389c-2fd3-4c6d-abd9-351b4435aba2)

This appears to happen due to this line:
https://github.com/muchimi/JoystickGremlinEx/blob/407786660da660d03790ae55c6b4423db33a8d0a/action_plugins/map_to_keyboard_ex/__init__.py#L197

`_get_display_keys` includes a line that also incorporates the +, but that is between the keys so makes sense:
https://github.com/muchimi/JoystickGremlinEx/blob/407786660da660d03790ae55c6b4423db33a8d0a/action_plugins/map_to_keyboard_ex/__init__.py#L502

To make it more obvious that it isn't a key, perhaps changing line 502 to use a bolded + would make more sense:
````python
        text += " <b>+</b> ".join(names)
````
and I would remove the + from line 197:
````python
        text += f" {self.action_data._get_display_keys()}"
````

**Comment by muchimi** [comment]
Here's how we're going to solve this as the same issue exists potentially with other keys:
![image](https://github.com/user-attachments/assets/ad48bb61-d247-4174-a03d-e16df966173c)
This will be in the next patch.  Thanks for suggesting the enhancement.

**Comment by muchimi** [comment]
Proposed solution in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m41.zip

**Comment by Tsudico** [comment]
The solution should make it obvious which keys are in the combination. Looks good to me and verified in m41.
