### ISSUE TITLE
Two axes read wrong

### ISSUE THREAD

**Issue by Lucarrrrr** [muchimi/JoystickGremlinEx#218]
The axes X and Y on my WinWing F-16EX Joystick are suddenly read wrong. They react stuttering and are not usable.
They are working fine in the calibration tool anSimApp Pro and where I calibrated them before correctly. Other axes are not involved. My work around is using them directly in DCS. Not so nice.
Thanks for your great job!

https://github.com/user-attachments/assets/601cde2f-13a9-47f6-9b51-7363bb041794

**Comment by muchimi** [comment]
I have a question - why are you calibrating?  I assume in this case it's because the WinWing base isn't hall effect so some sort of input processing is needed?

I suspect if you clear the calibration data things will be good again.  I am thinking at some point of enhancing the calibration piece with the input curve feature on the axis as the calibration data may mess things up more than it fixes in my experience.

If you can use DCS directly without calibration, this points to potentially bad calibration data in GremlinEx so I would delete that and see how far you get.

**Comment by Lucarrrrr** [comment]
Sorry, you misunderstood my small video. I'm using 5 of my 13 WinWing devices with 33 Axes alone. All have to be calibrated by SimApp Pro exactly, especially the throttles with idle, MIL and afterburner detend. All are fine. I checked all of them.
The two Joystick axes x and y are fine in DirectX, DCS and the calibration tool of JSG which I showed you as reference. Only the values on the left side (Axis (1) Y and Axis (2) Y) are totally exaggerated. Also I don't need there any Response Curve (EX) because the devices are precise as hell. I use them only for mice moving by sticks often.
I don't remember calibrating the stick in JSG. If there is accidently any calibration information in JSG, how can I delete it?
By the way. Since a short time I mentioned the A10-C 2 to climb constantly in DCS inspite of correct centering in the control settings in DCS. This may have other reasons.

**Comment by Lucarrrrr** [comment]
I only calibrate my devices once in SimApp Pro, which is important to be done once.In the App, DCS, Conrol Panel and the calibration Tools in JSG the axis input values are correct. Only in JSG itself they are totally exaggerated. So remaping to a vJoy axis will result in unusable axis in DCS.
I only wanted tto show you the real values reflected in the calibration tool.
As I always map axises for DCS for clarity like all buttons and hats it will be the best to have the opportunity to use Response Curves from JGS, too.
This effect appeared suddenly.
Are there any calibration data in JSG I'm able to delete?

**Comment by muchimi** [comment]
The calibration data UI has been updated and you can now see what is being input and how JGEX changes it.
I note also that JGEX can only get values as reported by DirectX (DInput) so if you have a utiltity that changes these values - it may  get bypassed.  The live view of the input in the calibration window will show you exactly what JGEX is "seeing" and can act upon.
Hope this helps.
