### ISSUE TITLE
Changing the "Trigger Delay" in "Gated Axis" generates an error

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#220]
Changing the "Trigger Delay" generates an error:

Uncaught exception:
Traceback (most recent call last):
   File "gremlin\gated_handler.py", line 4545, in _delay_changed_cb
 AttributeError: 'NoneType' object has no attribute 'delay'

![image](https://github.com/user-attachments/assets/9857e7dd-0d64-4618-89ca-7955a6ade974)

**Comment by muchimi** [comment]
Proposed solution in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m41.zip

**Comment by muchimi** [comment]
Marking this resolved pending additional input.  We can re-open if the problem persists.
