### ISSUE TITLE
Setting Action for a Gate in "Gated Axis" not working well

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#221]
When setting action conditions for "inc" and "dec" in the "Gated Axis", only one is registered (dec), and the "inc" is ignored.

![image](https://github.com/user-attachments/assets/d151bcf1-e58f-4a57-8bec-a71fd580b481)

**Comment by muchimi** [comment]
This has been resolved in m41.

**Comment by muchimi** [comment]
Proposed solution in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m41.zip

**Comment by muchimi** [comment]
Marking this as resolved pending further input.
Most current release is
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
