### ISSUE TITLE
JG Ex 13.40.16 m40 - OSC Inputs incompatible with Parent Mode changes

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#224]
The plugin mentionned in the previous issue was used to command mode changes via the streamdeck to JG Ex.  The following 2 OSC messages were setup in the plugin :
![image](https://github.com/user-attachments/assets/684d581f-b0e0-4cf7-8ae2-b15bcd56414a)
![image](https://github.com/user-attachments/assets/25421c42-1b8c-4e7d-a1a3-74f824e05ce3)

In JG Ex, the mode Ship is the parent of the mode Gnd.
Intent was to cycle between the two modes using those buttons on the streamdeck.

In the Mode Ship, two OSC inputs were setup :
![image](https://github.com/user-attachments/assets/41cbcc13-6d49-4813-90af-8fb90b57f329)
![image](https://github.com/user-attachments/assets/14b52ba0-a6a6-491b-9063-eed5bc891484)

JG Ex was launched and intiated with Ship as the runtime mode.

Switching to the Gnd mode was as expected.  However, it was never possible to switch back to the Ship mode.
Switching to the Gnd edit mode using the Profile Edit Mode drop down menu resulted in the following:
![image](https://github.com/user-attachments/assets/08bcecb5-7c7a-40ee-9020-b7421e79d282)

The OSC Input that was last selected in the parent mode remained displayed in the action window, however, no associated input was visible.

Therefore it appears that using OSC inputs to change parent modes is non functional.  I will try further testing with non-nested (non parent) modes.

**Comment by muchimi** [comment]
I just tried your command setup and it was functional for me (once I fixed the other textbox issue that was throwing an exception in message+data mode). 

I uncovered however that the Streamdeck is sending a press but not a release, unlike touch surfaces like OSC/Pilot and Touch/OSC.  So when you press a button on those (there are two commands sent, the arg is 1.0 for pressed, and 0.0 for release.
On the JGEX side, what's happening most likely (I didn't try the mode change, I tried the button action).

That means I likely have to add an auto-release option in the OSC layer to "pulse" the input - so auto-release it when it gets a press.

![image](https://github.com/user-attachments/assets/ba269e6c-cabf-4f68-8598-1602ff28c37e)

![image](https://github.com/user-attachments/assets/6c48b0a6-3572-484c-9b6e-d2e4456bfa79)

**Comment by muchimi** [comment]
Here's what it looks like OSC traffic-wise:
![image](https://github.com/user-attachments/assets/c2720076-b90a-48fa-bbd4-6188bc5ed974)

**Comment by muchimi** [comment]
Autorelease checkbox added.
What this will do, in button mode, is to issue a release trigger when the OSC input is received so when mapping to a key or a button, there is a corresponding trigger to release it if the input OSC doesn't send two commands.
The delay box determines how fast the release trigger occurs after the OSC message was received.

![image](https://github.com/user-attachments/assets/fdaa1e61-5904-4a8b-bf70-7a7d47ca5658)

**Comment by Lolo401** [comment]
Tested with m46.  Same issue:

(1) Setup multiple modes with at least one mode as parent.
(2) Add an OSC input in the parent Profile Edit Mode.
![image](https://github.com/user-attachments/assets/98c34a08-439a-4bac-8ec1-21b503d485ab)

(3) Switch to a child mode
![image](https://github.com/user-attachments/assets/d5888b8c-7e65-4830-af14-55f75f11e8a4)

(4) The Action window is still visible but the OSC input disappeared.  Switching modes disables all OSC inputs until the parent mode is selected.
![image](https://github.com/user-attachments/assets/731d8ae6-0b7d-4f9a-84c4-28e6abb397ed)


It appears that OSC inputs do not apply to submodes if edited in the parent mode.

**Comment by muchimi** [comment]
OSC, MIDI, keyboard are now aware of profile mode hierarchies as of m48.
Please see if this fully or partially resolved in:

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
