### ISSUE TITLE
13.40.16 (m41):  ERROR:  Unable to launch user plugin due to an error: 'Profile' object has no attribute 'get_last_mode'

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#225]
The above error message is generated:
![image](https://github.com/user-attachments/assets/af21de60-b1f2-433f-9a12-43ed66ab702c)

This happens in trying to set either of the below settings, saving and running the profile.

![image](https://github.com/user-attachments/assets/b07d007a-c56d-445b-8f5b-9fab887d7310)

![image](https://github.com/user-attachments/assets/94ad7735-c761-47d8-a1ee-5a69a6f7c5df)

**Comment by muchimi** [comment]
Resolved in m42.  Also fixed the error message as this is not user plugin related.

**Comment by ZK-273** [comment]
@muchimi Still when ALT-TAB'ing in and out of the game, JSG EX keeps the mode when Tabbing out of the game, but when I Tab back into the game, it resets to the Default Profile and doesn't stay on the current profile.

**Comment by muchimi** [comment]
Please see if resolved in m44.
