### ISSUE TITLE
(m43) output curve issue

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#227]
output curve has no effect in m43 or so it seems

**Comment by muchimi** [comment]
Which output curve (there are now three ways to set curves) :)

**Comment by muchimi** [comment]
Map to vjoy is my guess.  Fix inbound.

**Comment by daganael** [comment]
map to vjoy yes and the default one (which is also mtv I guess)

**Comment by muchimi** [comment]
Resolved in m44.  The curve execution order is listed under the calibration section of the docs.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m44.zip

**Comment by daganael** [comment]
nop stilll the same issue in m44
still have no output curve applied anywhere (neither default or specific). Vjoy remap + response curve Ex

**Comment by daganael** [comment]
my bad : the default output curve seems to work. Can't manage to make 'Response curve Ex' to work
