### ISSUE TITLE
background process not killed on exit

### ISSUE THREAD

**Issue by daganael** [muchimi/JoystickGremlinEx#230]
as shown in the screenshot below, when exiting JG (m44) the app is killed but goes to background processes despite not being 'reduced' but exited and stays there until manual kill.
see as it's not in the background app but still in the background processes

![{6F93910A-DE1A-4F7F-8CB6-3CA98A07A71B}](https://github.com/user-attachments/assets/322a672d-3ccf-4bbd-aa85-51cdffa02ac5)

**Comment by muchimi** [comment]
It will probably not surprise you that I am unable to duplicate (this said I haven't tried 44, I tried 45 and 46).
If the process remains, it means that Python is not exiting - the question is - why.
The log file should tell us what's going on, however please use m45 or above and enable verbose mode.

We are looking for these entries in the log file (system.log located in the gremlin ex user profile folder):

GremlinEx UI terminated
Terminating GremlinEx
DILL: input stop listen

**Comment by daganael** [comment]
gonna try my best :D

**Comment by muchimi** [comment]
So I was able to duplicate by pure luck, by running two copies of gremlin ex concurrently.  Investigating.

**Comment by daganael** [comment]
ok what I have so far is : it ony happen if the profile is activated when JG is exited.
If not the process is removed after 20 seconds or so
if a profile is activated when JG is killed I have this and the process stays on

![{0B2A67E7-F60E-4FB1-8583-6D28A9D0005E}](https://github.com/user-attachments/assets/ebf321d8-be96-4d6f-afe1-aa4b80dc7d4d)

**Comment by muchimi** [comment]
Ok that helps a lot - so we are not terminating a thread somewhere on exit.  Is this with m47?  M47 fires off an extra event when JGEX is being terminated to also stop any running profile.  Wanting to know if that makes a difference as this is the equivalent to stopping the profile before exiting.  I'll check the logic again today to make sure all threads receive the kill order.

**Comment by daganael** [comment]
was testing on m45 I believe. can test on a more recent vesion if you like

**Comment by daganael** [comment]
I confirm it's the same in m47 exactly the same log output

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m47.zip

**Comment by daganael** [comment]
well done !
