### ISSUE TITLE
(m47) the inputed value in the scale option for relative axis in Vjoy Remap can't exceed 1.000

### ISSUE THREAD

**Issue by AKOPOPS** [muchimi/JoystickGremlinEx#231]
for whatever reason it's caped at 1.000

**Comment by muchimi** [comment]
Thanks for reporting.  I need to review the scale function.

**Comment by muchimi** [comment]
Resolved in
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m47.zip

**Comment by AKOPOPS** [comment]
it's working as intended , thanks a lot for your work

**Comment by AKOPOPS** [comment]
new issue, the inputted value isn't saved to the profile

**Comment by muchimi** [comment]
Let me look into that.

**Comment by muchimi** [comment]
Found the issue - resolved in m48.  Here's a test version.
https://github.com/muchimi/JoystickGremlinEx/releases/download/test/joystick_gremlin_13_40_16_m48_test.zip

**Comment by muchimi** [comment]
Most current version.  Will close this unless the issue persists and we can re-open.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
