### ISSUE TITLE
m40 - Random OSC Server shutdown

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#235]
The following is observed when using OSC messages to change modes:

2024-12-15 16:09:16       INFO ACTION SWITCH: mode switch to [L. FOOT-EVA] requested
2024-12-15 16:09:36       INFO OSC: server shutdown
2024-12-15 16:09:36       INFO OSC client stop
2024-12-15 16:10:07       INFO OSC client stop

It does not occur consistently but will typically happen after a few minutes of playthrough.  All OSC messages are disregarded.

**Comment by Lolo401** [comment]
Wilco. Busy downloading.

**Comment by Lolo401** [comment]
OSC inputs is no longer working in m47.  All OSC messages are ignored and let unprocessed.

I tried enabling Verbose OSC log but enabling Verbose resulted in this error:
![{E465E5BB-968F-4B06-8FCC-E30223ABD76D}](https://github.com/user-attachments/assets/80d06650-9901-45b4-a836-ace4cc1f6672)

**Comment by muchimi** [comment]
Have you tested this on a new profile by any chance?  I verified functionality yesterday before posting m47 (and in fact used in in MSFS 2024 for several hours without issue).
I have added addtional diagnostics line to the generic error on profile start to shed some light as to what it didn't like.
Another API improvement is the OSC ports are now tied to the heartbeat ticker to keep them alive in case the operating system decides to shut down ports after some period of inactivity.

This will be in m48_test shortly so you can diagnose what's going on with the profile.

**Comment by muchimi** [comment]
Test m48:
https://github.com/muchimi/JoystickGremlinEx/releases/download/test/joystick_gremlin_m48_test.zip

**Comment by muchimi** [comment]
Updated:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m48R.zip
