### ISSUE TITLE
JG EX 13.40.16ex m48 - Enabling Verbose OSC debug creates an error at profile start

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#238]
The following error was observed anytime verbose OSC was enabled:

![{6DFC613E-C9EE-470A-B645-97B42157E949}](https://github.com/user-attachments/assets/3a52c1b3-34d3-4388-84ba-1e7c354930b8)

Disabling verbose or enabling any other verbose options (excluding OSC) would not trigger the error.

**Comment by Lolo401** [comment]
Note: acknowledging the error results in a correct profile start and run.

**Comment by muchimi** [comment]
Resolved in m50/m51.
