### ISSUE TITLE
MIDI input events not triggering actions

### ISSUE THREAD

**Issue by screamliner787** [muchimi/JoystickGremlinEx#239]
I have Behringer X-Touch Mini device. Joystick gremlin properly recognizes MIDI Input events (so does MidiOx). But if I add any action (remap, or even play text to speech) to midi inputs, they don't work. The same actions work with keyboard or joystick input events. If that is any help, i am also using SPAD.next with this midi device and all works in there.

**Comment by muchimi** [comment]
Thanks for the report - we've been focusing on OSC of late in 16 and not done a lot with MIDI for a pair of versions.  
I'll look into the MIDI layer and see why it's not triggering.
This will be resolved in an upcoming patch soon.

**Comment by screamliner787** [comment]
Thanks for quick reply :) for the moment I used OSC as a workaround - first spent couple of hours to find a MIDI->OSC bridge that actually works -> [https://github.com/Andymann/ofxOscMidi](url) Perhaps you would want to add the reference in the docs - its useful as it can also normalize OSC values. My Midi device sends CC values of 1..127 and JGEX expects 0..1. This bridge can do the normalization automatically. In the future releases, the ability to specify input values in other ranges than 0..1 could be super useful :)

**Comment by muchimi** [comment]
Tested as of m50 with OSC and MIDI:

https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m51.zip

**Comment by muchimi** [comment]
Tested with m53 as well.
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m53.zip
Closing the issue.
