### ISSUE TITLE
Unable to get this version of JG to work

### ISSUE THREAD

**Issue by paulheu** [muchimi/JoystickGremlinEx#240]
I've had to fiddle with vjoy versions to get the 13.3 build of JG to work by copying the x86 dll for vjoy into the folder, but this is not working for EX.

I have vjoy 2.1.9 installed currently and replaced the vjoyinterface.dll file in the JG folder with the x86 version from the vjoy 2.2.1.1-SDK, but this seems to not work for JG EX with either the x86 (throws error) or x64 (does not work) version.

Is this a known issue on WIN11 and is there plans to fix this? Woud love to use JG EX, but am stuck with the "old" verison of JG as it is.

**Comment by paulheu** [comment]
I tested this following the exact instructions and versions in the documentation with same result.
No output form vjoy using Gremlin EX while the 13.x build of "regular" JG works fine

**Comment by muchimi** [comment]
Thanks for reporting.  Can you include the log file in verbose mode (set up verbose mode in options)?
The DLL included in GremlinEx is for the very specific version of VJOY that is known to work with GremlinEx.
The log file should tell us what's going on, including any version mismatches.

There are several differences with the original Gremlin:
- it uses more recent versions of drivers and DLLs
- it uses the 64 bit versions
- it was tested only with the versions below who are known to function on various versions of Windows.

If you copy DLLs in/out of the GremlinEx folder to "fix" the issue - something is probably off with DLLs - unless they are the specific version - I suspect you will run into issues.  The VJOY version expected is 2.1.9.1 64 bit.  That is the version known to work with the latest Windows 11 24H2 and other versions are known to have issues, including a more recent version of VJOY circulating on the internet.  If you use HIDHide, the version we're looking for that is known to work is 1.5.230.0.

This doesn't mean other versions will not work - it just means that they are untested.  I know for a fact that the "newer" version of VJOY on the internet has conflicts with Windows 11 24H2 (it won't install or load correctly) although that seems to be heavily system dependent.

The system.log file will display what versions were found in the DLL, both for VjoyInterface.dll and the included DirectInput python interface which is 1.4.0.0 (and different from the one used by the original Gremlin).  That file is found in %userprofile%\joystick gremlin ex.

Hope this helps, and let's take a look.

**Comment by paulheu** [comment]
I actually did a full Windows reinstall (was due anyway;) ) and now things work as expected.. Config wise nothing changed, just a full fresh install.. could be an OS issue, could be just that I installed JG and everything else fresh again.. but it works..
