### ISSUE TITLE
JG Ex 13.40.16Ex m49b - Setting a Center Deadzone in a response curve results in an error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#243]
The following was observed in m49b whenever a center deadzone was modified:
![image](https://github.com/user-attachments/assets/2b132c34-b78e-4022-bbd2-1109fb6367d9)

It has not been tested on m50_test_2.

**Comment by muchimi** [comment]
Thanks for reporting.

**Comment by muchimi** [comment]
Resolved in m51 with a new option to force centered mode on non-centered curves.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m51.zip

**Comment by muchimi** [comment]
Closing this - we can re-open if the issue persists.  Current version:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m53.zip
