### ISSUE TITLE
M50/51 not detecting HAT inputs

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#248]
In m50 and 51, the HAT input is not recognized by JGEx. It is working fine in m49b.

![image](https://github.com/user-attachments/assets/3b5f910b-6871-41a6-be0f-59701f69eb5e)

**Comment by muchimi** [comment]
This is resolved in 
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m52.zip

**Comment by muchimi** [comment]
Closing this issue (tested in m52/m53).
