### ISSUE TITLE
VjoyRemap button press with Tempo not behaving as expected

### ISSUE THREAD

**Issue by alex-smtv** [muchimi/JoystickGremlinEx#3]
Hello!

When using a Tempo logic and fitting a VjoyRemap the button press won't behave as a 'click'. When I press the physical device button it will outputs the vJoy button press, but it won't depress it. The vJoy button is pressed forever and even when pressing again the physical device button the vJoy button will keep its pressed state. 

![image](https://github.com/muchimi/JoystickGremlinEx/assets/13024466/daffd8bd-1b00-4ed4-a5b3-7dfc7a6ccb16)

Additionally unrelated to the issue, I wanted to point out that 'Button Press' and 'Pulse Button' are duplicated in the Mode list:
![image](https://github.com/muchimi/JoystickGremlinEx/assets/13024466/53c19e88-daea-41de-ab1c-9fd37bbf430e)

**Comment by muchimi** [comment]
VjoyRemap is not technically designed to work with Tempo.  There is a pulse option to pulse a button you may try with Tempo.
Pulse Button is what behaves as a temporary press/release.   Button press is a hard press until it's unpressed, which is a separate event and Tempo will probably prevent that from beeing issued.  The default Remap would probably work better with Tempo as Tempo was designed to work with Remap, VjoyRemap was not.

That doesn't mean it shouldn't so I'll look into that but definitely not tested with Tempo (because the default remap should function with that).

I'm looking to see what's going on with duplicated lists.

Thanks for bringing this up.

**Comment by muchimi** [comment]
The duplicate items are removed and the release updated to include that.

**Comment by muchimi** [comment]
I've tested VjoyRemap with Tempo and it seems to work for me.
Tried with Press and Pulse.
The difference if I had to make sure this occurs on press, not on release.  Perhaps that's the difference?
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/e0127c6b-39f6-43c5-b98f-fea757f8984f)
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/1e4e0267-1578-4485-b47d-f358194a6e14)

**Comment by alex-smtv** [comment]
https://github.com/muchimi/JoystickGremlinEx/assets/13024466/3d9a69b0-5b29-4d25-ad34-36f40ab18176

Here how it looks on my end. I only did one quick click on my physical device and as you can see the vJoy button is held down.

**Comment by alex-smtv** [comment]
So here's an update of what I've been testing. Activate on press seems to work. I had it bugging and it was difficult to reproduce, but I think it was related to a plugin I had forgotten to filter out, if it happens again I'll let you know but I think it's good.

But there is a catch even if activate on press works. By concept (and not by error) activate on press simulates a different behavior than activate on release. Activate on press will held down the button of short + long press when in long press state. Activate on release will held down only button of long press when in long press state. Quick example: short press mapping to vjoy btn 1, long press mapping to vjoy btn 2. Long press with activate on press = vjoy btn 1 + 2. Long press with activate on release = vjoy btn 2. Short press will result with vjoy btn 1 regardless.

So if I come back to the idea of using activate on press, it works but is not the solution to the original issue with activate on release.
