### ISSUE TITLE
GUI missing graphics / icons

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#34]
Missing button labels in the plugins section:

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/7c465536-a804-41ee-bb81-bb850594136f)

Missing graphics identifying if a button has been mapped:

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/0b4fdd5f-675c-4e4b-8fc9-8f14b044f022)

**Comment by muchimi** [comment]
Thanks.  Please attach the profile so I can tell how it's attached and why the icon is returning a null value (that happens when it doesn't understand the input type usually).  Each module returns the icon based on the mapping, and the default is no icon if it's either not mapped or doesn't know how to do this.   Come to think of it I may change this default behavior to return a generic icon in case it's confused so at least the code can tell you "I have no idea what this is".

**Comment by Lolo401** [comment]
The only action not resulting in a label  is the 'legacy' remap (blank space highlighted in red)

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/b2ca5424-ebb1-4f5b-a7bf-694789424fce)

[VPC_LEDs - Copy.txt](https://github.com/muchimi/JoystickGremlinEx/files/15123295/VPC_LEDs.-.Copy.txt)

Attached is the plugin file (extension changed from py to txt) for the missing button labels.

**Comment by muchimi** [comment]
I've tested this and not seeing any issues with the legacy remap finding its icons (shown here using an axis map and a button map on a Virpil stick)
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/9f7072ea-ba4e-491c-894d-68aa4d4e88c6)

I also ran the VPC led plugin without issue.  I reviewed the code, which essentially looks for axis, button or hat mapping on the raw input and determines based on that the icon to pull, and the icon is in the gfx/icons folder under the remap action plugin.  So one thing to check is that the icons are indeed in that folder.

![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/5355af24-1746-4732-8277-39fa4b8a0d23)


I am working on a small modification (pictured) to pull a generic icon if the file isn't found.  I'm also looking at creating these dynamically as QT can do this IIRC.

So nothing very evident from my testing so far as to why your icons are gone - the theory is - the icon files cannot be found.

**Comment by muchimi** [comment]
Code update in pre-release includes generic icons and improved logging in case an input condition isn't known so an icon cannot be derived.  The two things icons need to know is the type of raw input this is and the input ID.

That should hopefully get us somewhere on this topic.

**Comment by muchimi** [comment]
Just had an Ah - HA moment.  Turns out the icons work fine in non compiled mode so the culprit is the packaging.
I have a solution I think...  Stay tuned.

**Comment by muchimi** [comment]
Looks like the packaging changed a bit, and I have additional logic for VjoyRemap and the legacy Remap to look for their icons and, importantly, report back why it cannot find something in the log file (and where it was looking).
Try this (updated a few mins ago):
https://github.com/muchimi/JoystickGremlinEx/releases/tag/10.40.10ex

**Comment by Lolo401** [comment]
Just tried the linked release and got this at first start attempt: 

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/a8d8bb86-e09f-4718-99f2-4e29ca7bc332)

**Comment by muchimi** [comment]
Fat fingered that one.  Should be fixed (famous last words) in the latest 10.40.10ex.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/10.40.10ex

**Comment by Lolo401** [comment]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/fb0c930f-8927-4ef3-a55f-2f69ce93d06a)

The screenshot here above:
   (1) On the left, Joystick_gremlin.exe 13.40.10Ex downloaded 27 Apr 24 at 2325Z
   (2) On the right, joystick_gremlin.py 13.40.10Ex Dev branch running on VSCode with Python 3.12.3. 
   
The same profile is run simultaneously with both versions running at the same time.  

The .exe file would trigger the error.  The DEV branch would not.

Of note:  I have not yet managed to get all the UI icons to show up in the dev branch as shown by the Activate label replacing the icon.  However, this does not trigger any warning while mapping.

**Comment by Lolo401** [comment]
Of note: Since the errors pop up at the center of the screen, I was able to isolate the error the EXE version by running both versions separatly.  They were run simultaneously for the prupose of the screenshot

**Comment by muchimi** [comment]
Helpful, thanks.  Another place an icon is used.  QT can be - as we say - a challenge.  The screenshot is very helpful.

**Comment by muchimi** [comment]
13.40.11ex  fixes a "sizing" issue related to the port to QT6 and behavior changing.
Set minimum icon size if the icon is not found (for whatever reason) and hardened the code to handle missing icons.
Still not perfect but the logic is there and this seems to be functional for me now in compiled mode with the new packager.
QT was just not able to find icons on its own so needed a bit of code help for the packaged mode that added another folder to the mix (which doesn't exist when not running in packaged mode - eg - direct from the script).
