### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by magocalypse** [muchimi/JoystickGremlinEx#35]
I searched under closed issues and noticed a issue marked as closed crashing with modes, when switching modes I am getting the below error. Sorry if this is repeating a known issue already.

It might be a configuration issue on my end, just recently started using this tool. In the base Joystick Gremlin was not having this error, being able to set the start axis value is why I switched to this Ex thank you. 

Been using 13.40.4 and get this error anytime I go to switch modes to edit mappings, it does not prevent the modes from working with the bindings. To make sure it wasn't just my profile, I downloaded 13.40.9 and tested with a new blank profile, creating a new test mode and attempting to switch into it has the same error. 

![uncaught exception](https://github.com/muchimi/JoystickGremlinEx/assets/168148026/782616e3-41c6-4ecf-9589-21a5fb75441a)

**Comment by muchimi** [comment]
Hi, thanks for reporting.
There have been a few releases since that version including a pair of bug fixes that address mode issues.  Can you try the latest pre-release (which is quite stable and is my daily runner for now - it's only pre-release because of a new container) to see if the set_mode issue has been resolved?  If the issue continues, please attach your saved profile as it makes it easier to diagnose the exact mapping / module that you are using!)  Thanks.

Link to the latest version:

https://github.com/muchimi/JoystickGremlinEx/releases/tag/10.40.10ex

**Comment by Lolo401** [comment]
I am also encountering the same issue on a daily basis. I have experienced it with releases 13.40.4Ex onwards.

I have not reported it as it appears to be more a nuisance than anything else.  It does not affect my programming on my system at least.

**Comment by muchimi** [comment]
Hi, I just attempted to duplicate in 10.40.10Ex with no errors:
1) run JGEX
2) file/new profile
3) tools/manage modes
4) click on the pen icon and type in a new mode name (I changed mine from "default" to "test")

![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/88953ecd-22d6-4878-9c03-60db4e3c4134)

I also added a mode and renamed it and no issues either.  Did you attempt this in 10.40.10ex?

![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/36deb028-2f9e-47eb-8e8c-87135e74e3a8)

**Comment by muchimi** [comment]
One more note: 10.40.10ex is a dev branch pre-release so the version won't change but the download zip file will (along with the source code).  I'm looking to have the current issues resolved in this release and checking in changes/updating the zip as they are made, so do redownload the zip here:

https://github.com/muchimi/JoystickGremlinEx/releases/tag/10.40.10ex

**Comment by Lolo401** [comment]
I have downloaded the Dev source code and I am currently comparing my results using the dev and the compiled zip file.  (running on python 3.12.3) I'll endeavour to perform investigative testing between the two options when reporting bugs.  Can you just confirm that the requirements.txt is up to date and self-sufficient for dependencies ?

**Comment by muchimi** [comment]
The dependencies are also listed in the docs.

**Comment by magocalypse** [comment]
I downloaded and tested on a new empty profile with the Dev  [13.40.10ex] and did not encounter any errors with creating modes or switching modes. Thank you
