### ISSUE TITLE
Uncaught Exception: Traceback error when viewing axis with response curve

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#37]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/44e1c537-6d8e-4b77-8c1f-8233083b4412)

This error shows up whenever an axis with a response curve is selected in the UI of JG13.40.11ex.

How to reproduce:

Step (1): Creating new profile
Step (2): Bind an axis of any device using Vjoyremap
Step (3): Add a response curve inside the same container.

![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/ea3ecbb7-b46b-4848-8feb-42fa6c1176f9)

**Comment by muchimi** [comment]
I know what it is.  Patch inbound soon (tm).
Thanks for reporting.  I missed an instance somewhere for the new icon handling related to QT6 and packaged mode.

**Comment by muchimi** [comment]
Try this.  https://github.com/muchimi/JoystickGremlinEx/releases/tag/11.40.12ex
