### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by HiveLeader** [muchimi/JoystickGremlinEx#38]
JoystickGremlinEX is always be detected as a Virus! Iam the only one, who got this ?

![Screenshot 2024-05-28 190422](https://github.com/muchimi/JoystickGremlinEx/assets/58701470/43f0dec7-f038-40ff-ab02-9d0e5d6d1c40)

**Comment by muchimi** [comment]
Neither my virus scanner nor Google detected any viruses and I just re-scanned just to be sure.
One reason is GremlinEx is python based so script based.

This could be a false positive not knowing which AV solution you are using.  My internal testers have this software and have not reported this issue either.
