### ISSUE TITLE
Vjoy action condition not recorded when button set to "released""

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#41]
https://github.com/muchimi/JoystickGremlinEx/assets/157264378/6c91eb12-ab9b-4377-b0c1-e4f855199bbb

**Description:** 
Whenever a condition is set to a container or action and involves a Vjoy button condition, it is impossible to set the condtion to 'released' via the UI.  If the button menu is left after setting the condition to 'released', it is automatically set back to 'pressed'.

**Workaround:**
Editing the profile XML and changing the tag works as intended.  That is until the button is called up in the UI at which point it will revert back to pressed.

**Impact**
Not critical, more of a UI nuisance than anything else. However, the auto revert back to pressed when the button is inadvertently selected is frustrating.

**Note**
This issue has been present on every version of JG since 13.30 and every version of JG Ex since 13.40

Cheers,

**Comment by Lolo401** [comment]
Note: lousy video recording.  Look at the 10 last seconds for the issue.

**Comment by muchimi** [comment]
Thanks for reporting...  Will look at it.

**Comment by muchimi** [comment]
@Lolo401  I narrowed down the issue to a UI reset to default on reload, ignoring any prior valid values.
Try this pre-release - and I'll move it to full release if you can verify it fixed it.
I duplicated the settings on your video and the condition was not reset anymore to default on reload. 
The release is not visible by default unless you call up pre-releases:
Link: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.12ex_d

**Comment by Lolo401** [comment]
I have tested the pre-release both with a blank profile and my existing SC profile.  The profile has numerous actions conditions based on released / pressed states.  JG ex 13.10.12ex_d worked as per design.  The issue was no longer observed.

Thank you !

**Comment by muchimi** [comment]
I'll go ahead and publish it.  Thanks for responding. Also, the scroll bar is added to the selectors (left side) of the input viewer.
