### ISSUE TITLE
Input Viewer window not resizable vertically

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#42]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/8b8e7e9e-48d6-4751-b0fd-3781f1aa85e2)

**Description:**
As per title.  When using a large quantity of virtual devices, it becomes impossible to access the last ones due to the absence of scroll bars and option to resize.

**Workaround:**
None.

**Impact:**
Minimal, nuisance only.

**Affected builds:**
All.

**Comment by muchimi** [comment]
Thanks.  Didn't touch that original code - looks like that dialog is in need of being plopped in a vertically scrolling window.  Will look at it.

**Comment by muchimi** [comment]
Feature added in 13.40.12ex revision (c).

https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.12ex
