### ISSUE TITLE
Unhandled exception in script.

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#43]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/ff445132-68fe-4f11-82ab-be4b2118d8f7)

Currently investigating an issue with the error reported above.  Will provide conditions when isolated.

Debug file attached

[debug.txt](https://github.com/muchimi/JoystickGremlinEx/files/15490271/debug.txt)

**Comment by Lolo401** [comment]
Note: Using pre-release 13.40.12ex_d

**Comment by muchimi** [comment]
Hmm, looks like the dll didn't make it.  The dll didn't change.  the path should be: [install folder where exe is]\_internal\dill.dll
