### ISSUE TITLE
Missing icons in the Macro container

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#44]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/f3664da3-e789-43ce-9960-cb6332c57ff0)

**Test Conditions:**
JG 13.40.12ex_d 

**Description:**
The icons associated with creating and deleting actions are missing and the space is blank.

**Workaround:**
None.

**Impact.**
Minimal. The buttons are still functional when clicking in the blank space.

**Comment by muchimi** [comment]
Who knew not all icons were in the same folder as the plugins?  Reworked logic to search for icons beyond the plugin:
Please verify this resolve this issue:
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.12ex_e

**Comment by Lolo401** [comment]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/79dd9f96-7120-4ccb-bf54-0970dc3569e1)

Fixed.
