### ISSUE TITLE
Uncaught exception: Traceback when running macro's using Hold / Toggle / Count options

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#45]
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/5d1bb811-bfa7-4bb0-bcf8-9e54bdf243e9)
![image](https://github.com/muchimi/JoystickGremlinEx/assets/157264378/dda75580-a564-42f3-b06b-b6b238e61e07)

Description:
The error here-above was observed anytime a macro was created using a Hold / Toggle or Count option in the macro settings.
Upon activation of the macro using the associated keybind, the macro would get executed and the message would pop-up simultaneously.  If the macro was set to Hold, it would loop continuously.

How to reproduce:
(1) Create a macro with a blank profile;
(2) Set a Hold / toggle or Count setting;
(3) Activate profile and activate keybind.

Impact:
Moderate. Although the macro is being run, the pop-up will trigger a return to windows and cause cascading issues.

**Comment by Lolo401** [comment]
Note: At the time the issue was discovered, a macro was created to trigger an endless repetition (some sort of an anti-afk).

**Comment by muchimi** [comment]
Proposed fix in 
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.12ex_f

**Comment by muchimi** [comment]
Marking as completed as of 13.40.12ex.
