### ISSUE TITLE
How hard to have SimConnect Python API in plugins?

### ISSUE THREAD

**Issue by aspence** [muchimi/JoystickGremlinEx#46]
Hey Muchimi it's so awesome that you have put work into JG, I love this program and agree with you on the whole approach - so smart. Thank you. 

Would it be hard to bring the dlls or python modules necessary to be able to use SimConnect interfacing with MSFS2020 directly inside JGEx plugins?

I've seen example code to use a python SimConnect API and realized if it were inside JGEx plugins it would simplify a billion things for fs2020. I think.

Thanks for any input!

**Comment by muchimi** [comment]
I played a while back with SimConnect as a script (as I did with OSC).  I think the approach is more to support SimConnect as an output device as it is with vjoy so the general JGEX mechanics fit as there aren't too many output options for SimConnect from a data standpoint - there are however a dynamic number of variables that vary with MSFS patches as well as add-ons. and it varies per MSFS session depending on how you load the sim.   So one challenge is the ability to get custom variables as options as the brute force method (read every add-on configuration) can take a very long time.   Not a small amount of work but feasible I'm sure.  This would give JGEX the same functionality as AxisAndOhs and SnadNext so feasible for sure.  I'll put this on the wishlist.  Thanks for suggesting.

**Comment by muchimi** [comment]
I have started work on this.

**Comment by aspence** [comment]
Wow! This is tremendous. Thank you! Also, the other improvement you made to have Ex in a separate folder from standarg JG is so helpful. Cheers

From: muchimi ***@***.***>
Date: Friday, June 7, 2024 at 3:30 PM
To: muchimi/JoystickGremlinEx ***@***.***>
Cc: Andrew Spence ***@***.***>, Author ***@***.***>
Subject: [External] Re: [muchimi/JoystickGremlinEx] How hard to have SimConnect Python API in plugins? (Issue #46)

I have started work on this.

**Comment by muchimi** [comment]
Update:
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/afdff28f-5707-468a-9de1-1f471ec8e683)
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/10134787-ea0b-4112-9a44-783cf2c8e5ec)

**Comment by muchimi** [comment]
I've included in the pre-release below the first work-in-progress iteration of this.
It's still very much an in-progress feature and I was able to successfully control my Cessna from within GremlinEx mappings.
The UI is preliminary and not all the features may be functional (and some may indeed blow up) but I wanted to at least include where I am with this as it is now bare-bones functional and tested with axis outputs (so mapping to axis outputs).

I'm sure it works with other axis outputs as well - what has not yet been tested well and still being coded are the singular actions (example, raise or lower gear).

https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by muchimi** [comment]
m12 pre-release includes the following features, while this is still very much a work in progress.
- ability to curve output to Simconnect (see screenshot below)
- ability to trigger switches, set them on/off or toggle them.

The list of variables GremlinEx can send is defined in an XML file.  That file is built automatically if it doesn't exist but won't include custom simvars.  These simvars can however be manually added to the XML - at some point an editor will probably be helpful to have but that's a future feature at this point as the module is still working on the basics.

Example of a curved output to the aileron axis:
![image](https://github.com/user-attachments/assets/f02cbd3e-6e8a-4279-b0b4-4a88e5d24dc9)

Example of the toggle mapped to a joystick button to toggle beacon lights.
![image](https://github.com/user-attachments/assets/88cf30fe-7a8f-4ec0-8b7f-be6804ecb5a7)

**Comment by muchimi** [comment]
Pre-release m12 is posted - still WIP but tested ok with MSFS current version as of this writing.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
