### ISSUE TITLE
[Request] Allow Utilization/Specification of different config.json file for JoystickGremlinEX?

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#50]
I'm starting to work with JoystickGremlinEX.

If the config.json from JoystickGremlin is being also used by JoystickGremlinEX, is it possible that we can have the JoystickGremlinEX use a different config.json?

For me, I want to rename a copy of the profile I know that's working in JoystickGremlin, and have JoystickGremlinEX refer to that copied (renamed) profile exclusively for itself, without interrupting current JoystickGremlin operation.  This for testing and making any changes to the JoystickGremlinEX profile version without interrupting the current JoystickGremlin profile version.

This so that I don't have to keep renaming and pointing to the parallel test file each time I loadup JoystickGremlinEX for testing.

If I'm in error regarding the approach or my interpretation of how JoystickGremlinEX works with any of the config files from JoystickGremlin, please kindly educate me and let me know if there's a better way.

Thanks much!

**Comment by muchimi** [comment]
Excellent idea.  Profile folder changed.  Thanks for suggesting as it will allow running both the original and the EX without conflicts.
https://github.com/muchimi/JoystickGremlinEx/releases/edit/13.40.13ex
