### ISSUE TITLE
[UI MODIFICATION REQUEST]  -  Device Information  -MINOR-

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#53]
Please consider revising the Device Information UI in order to either:
1.  Have user-defined column widths
or
2.  Revise the column widths to:
2a.  Allow more space for the Name of the Device
2b.  Reduce Axes column appropriately
2c.  Increase GUID column to allow seeing full GUID Device Value

Thanks!

**Comment by muchimi** [comment]
Starting with 13.40.13ex (g) The device information window has been reworked to a table format, resizes to content by default, resizeable columns,  sorting, and context menu to copy cell content to the windows clipboard which is handy for GUIDs.

The script command at the bottom of the window is suitable for user plugin scripts as that will generate the necessary python and puts it in the clipboard as well.

The pre-release can be found here (note that any version after patch (g) will contain this feature so this link may be obsolete when a new patch/version is released.

https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.13ex_g
