### ISSUE TITLE
Autoload Profile

### ISSUE THREAD

**Issue by HiveLeader** [muchimi/JoystickGremlinEx#55]
I've got this, when iam using the autoload-function in Tools/Options/Profiles. The issue only appear, when autoload-profile is active.

Version: 13.40.13ex (h)

2024-06-09 14:11:01       INFO Found exact match for D:/DCS/bin-mt/DCS.exe, returning C:/Users/Admin/Joystick Gremlin Ex/DCS_NEW.xml
2024-06-09 14:11:15      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 548, in process_event
   File "gremlin\execution_graph.py", line 76, in __call__
   File "gremlin\execution_graph.py", line 175, in process_event
   File "container_plugins\tempo\__init__.py", line 266, in process_event
    self.timer.cancel()
    ^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'cancel'

2024-06-09 14:11:15      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 548, in process_event
   File "gremlin\execution_graph.py", line 76, in __call__
   File "gremlin\execution_graph.py", line 175, in process_event
   File "container_plugins\tempo\__init__.py", line 266, in process_event
    self.timer.cancel()
    ^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by muchimi** [comment]
Proposed fix: resolved in 13.40.14ex - should be out later today.

**Comment by muchimi** [comment]
Try: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14.ex

**Comment by HiveLeader** [comment]
> I've got this, when iam using the autoload-function in Tools/Options/Profiles. The issue only appear, when autoload-profile is active.
> 
> Version: 13.40.13ex (h)
> 
> 2024-06-09 14:11:01 INFO Found exact match for D:/DCS/bin-mt/DCS.exe, returning C:/Users/Admin/Joystick Gremlin Ex/DCS_NEW.xml 2024-06-09 14:11:15 ERROR Uncaught exception: Traceback (most recent call last): File "gremlin\event_handler.py", line 548, in process_event File "gremlin\execution_graph.py", line 76, in **call** File "gremlin\execution_graph.py", line 175, in process_event File "container_plugins\tempo__init__.py", line 266, in process_event self.timer.cancel() ^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'cancel'
> 
> 2024-06-09 14:11:15 ERROR Uncaught exception: Traceback (most recent call last): File "gremlin\event_handler.py", line 548, in process_event File "gremlin\execution_graph.py", line 76, in **call** File "gremlin\execution_graph.py", line 175, in process_event File "container_plugins\tempo__init__.py", line 266, in process_event self.timer.cancel() ^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'cancel'


This is fixed for me, but i noticed a strange behaviour, when i use the autostart-function, when a profile is already active.
When Joystick Gremlin Ex autostart a profile, when there's already a active profile, than Tempo-Actions will also press both, short and long presses.

I've done a screenrecord of this.

https://drive.google.com/drive/folders/1rykkFhMMLAe3IXxmkeBChn14JYEMHLgf?usp=sharing

**Comment by muchimi** [comment]
I'm not sure why autostart would make a difference vs manual start as it's the same code executing - one just does it automatically.

However, I've modified the two tempo containers to force a state reset whenever a profile is activated to make sure things get reset.  I'll have to investigate the behavior further as it may be a timing thing.  That change will be in the next pre-release.

**Comment by muchimi** [comment]
This has been refined a bit more in the updated pre-release https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
