### ISSUE TITLE
[13.40.14ex (prelim)] - 'Map to Keyboard EX' Action Partially Obscured on Window Resize

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#56]
Here is what it should normally look like:

![image](https://github.com/muchimi/JoystickGremlinEx/assets/141291139/38ed0518-f398-4268-9e21-7f21c632c938)

Here is what it looks like when the JSGEX Window is resized smaller in size:

![image](https://github.com/muchimi/JoystickGremlinEx/assets/141291139/14a8fbef-f86a-4d4c-89fd-4abb048cc83e)

**Comment by muchimi** [comment]
Resolved in https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex
The container/action view area will scroll horizontally if the action container cannot resize itself beyond a size that will fit the view.
That particular action has also been made taller by moving the delay options to another row to make it "fit" in smaller widths.
