### ISSUE TITLE
[ENHANCEMENT REQUEST] - [Keyboard Mapping] - Please extend adding keys with modifiers for the Keyboard Profile (also F13-F24) 

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#57]
Please consider allowing the user to specify key combinations for the Keyboard profile.

Currently the user can only choose one key when looking to assign something on the keyboard.
It would be useful to allow for modifiers (even the extended F13-F24) keys in this section.

Below is a screen shot of the area I'm speaking of.
For example, when pressing the 'Add Key' button, the user cannot specify any combo keys, like:  Shift + T
Nor can the user specify F13 - F24 function keys (unless they have a special keyboard, or use some other application to send the keystroke to JSGEX).

It would be nice to have the above added.  Thanks

![image](https://github.com/muchimi/JoystickGremlinEx/assets/141291139/637b251f-9c34-4a5f-a14f-a2f10f4ab0fc)

**Comment by muchimi** [comment]
The original keyboard handler does not support F13 to F24.
It should be easy enough to make it understand the new keys.

**Comment by muchimi** [comment]
Whelps!
Not easy - unless you have a keyboard that puts out these keys.  Sounds like this also needs a virtual keyboard.

**Comment by muchimi** [comment]
I've revamped the keyboard UI quite a bit, and to make it compatible with the other custom inputs, I'm adding MIDI and OSC inputs that use the same sort of custom input wiring/manip logic needed, so the keyboard, MIDI and OSC modules will use the same UI elements.

Here's a preview - I'm working through a few things as this was pretty much a gut-and-replace effort; it shouldn't be too long now, depending on how my internal testing goes with the new input modules.

![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/985278d7-607e-4570-827a-abba78e497fd)

**Comment by muchimi** [comment]
The new virtual keyboard that shows up when configuring keys.
![image](https://github.com/muchimi/JoystickGremlinEx/assets/32274043/e2c9360e-8d52-43ab-a1d4-734252bdeca0)

**Comment by ZK-273** [comment]
Thanks.  I'll test when ready.

**Comment by ZK-273** [comment]
Some thoughts:

Depending on the JSGEX Window size, will multi-key combinations be cut off due to spacing issues?

For example, if the user can enter something like:  Left Shift + Right ALT + DEL
Will that possibly get cut off 'visually' in the left side vertical panel?  Especially if there are a lot of action icons?
Would renaming the modifier keys LALT, LSHIFT, LCTRL etc help with this potential issue?  Instead of Left Alt, Left Shift, Left Control?

_i.e.  Would it work where the left side vertical panel shrink no smaller than its contents in order to preserve readability?
Would there be any value to allow the user to be able to also adjust the left panel horizontal size?  Things to consider?_

**Comment by muchimi** [comment]
Virtual keyboard available with revamped input configuration/edit in:
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_i
