### ISSUE TITLE
[BUG] Adding a Macro Action to a container with existing actions cuts off the K & M options

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#58]
When adding a Macro to an mapping that already has existing actions in the container, the Macro window is condensed and not expandable to reveal the K and M options for the Macro Mapping.

![image](https://github.com/muchimi/JoystickGremlinEx/assets/141291139/4e1bc00f-a93c-4aa6-afaa-8bc4d41278d3)

There are double downward arrows, but that doesn't allow to reveal the K & M

**Comment by muchimi** [comment]
Here we go again with scrolling lol.  Ok, I'll see if I can go tweak the UI for this action.  It should just be able to grow vertically.

**Comment by muchimi** [comment]
Fixed as of 13.40.14ex (c) (made the toolbar minimum size larger) forcing a scroll if the draw area is not tall enough.
