### ISSUE TITLE
error on startup with devices not plugged in

### ISSUE THREAD

**Issue by brammmers** [muchimi/JoystickGremlinEx#59]
Starting JSGEx with one or more devices not plugged in results in the following:

![Screenshot 2024-06-22 005512](https://github.com/muchimi/JoystickGremlinEx/assets/3657420/27658afa-0976-480d-8422-f31b3fe2070b)

It would be nice if this didn't happen, so I could start JSG with windows.

Could this be due to a user plugin python script I have? (I'm no good at python)

**Comment by muchimi** [comment]
Sounds like an issue with the add-on script somewhere.  The log file may give you an idea where the issue is, or you can post the code if you'd like so we can take a look at it.

**Comment by brammmers** [comment]
The only user plugin I have loaded is the one that you kindly fixed to make work with JSGEx in my other issue ... https://github.com/muchimi/JoystickGremlinEx/issues/14

Might be one of those "issues" that actually turn into a feature request: 'Restart plugins when a device becomes available.'

What do you think?

**Comment by muchimi** [comment]
So far, the only workaround without modifying the script is for it to detect device changes. 
I'll look into it if I have the time, but for now, if the third-party script does not function, the only "surefire" method is to stop and restart the profile.  Arguably, plugging and unplugging hardware while the control software is running is not directly supported, one reason is initialization and logic dependent on a specific device being there is not a predictable outcome - there are too many things that can go wrong there.

**Comment by brammmers** [comment]
Thanks for looking at it. I kind of expected this outcome.
