### ISSUE TITLE
[ENHANCEMENT REQUEST] - Auto Repair XML Profile Device GUIDs Upon a Change

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#60]
There are times when Windows will change a device's GUID which then will cause a GUID Mismatch between the user's XML profile and the new GUID assigned for the same device.  Joystick Gremlin EX (JSGEX) will detect the new GUID for the device, but will fail to work if the GUID isn't the same within the user's XML Profile.
This causes the need for the user to manually go in to the XML profile and replace all old GUID instances for their device with the new one that JSGEX detects.

Now, this isn't necessarily rocket science to manually repair the XML file.  However, depending on the user's savviness, the amount of times the GUID may change due to stick updates etc, and the complexity of the XML Profile.  This situation could start to become troublesome for the end user.  Starting to manually **edit** the XML Profile introduces more risk something may be broken unintentionally.

So I would like to propose the JSGEX have a feature that could make this process easy for the user.

Please hear out my idea of proposed high level functionality below:
-------------------------------------------------------------------------------------------
So.  The GUID changes typically happen if a device is disconnected and reconnected to the PC.  Windows may assign a new GUID for the same device compared to the previous one.

For example, with the VPC(Virpils) software, making any changes on the stick and saving them, causes those changes to be written to the Virpil stick base.  In this process, the Virpil stick base is programmed, disconnected and reconnected.  This is where a new GUID for the same device will likely be assigned.

This will cause a mismatch between a profile's GUID (former) for the same device and the new GUID that Joystick Gremlin(JSGEX) now detects for the same device.

There could be a comparison between the current GUIDs that JSGEX sees and the loaded Profile's GUIDs.
There are certain ways this could be handled.
JSGEX already can detect current device information it's allowed to see for connected devices.
Information like:
Device Name
Axis Count
Buttons Count
Hat Count
Vendor ID
Product ID
GUID

Device information already saved to the XML Profile file:
Device Name
Label {user defined}
GUID
Type

_**Given all the above data fields (combined with JSGEX possibly creating its own unique ID based on those values), something extra could be saved to the XML profile in order to help with the confirmation that the device didn't change, just the GUID did.**_

Also, currently the Devices' label field (user defined) is also saved to the XML Profile.

Additional information could be saved to the XML Profile File that could help JSGEX in verifying if the device in the XML Profile is the same device with the new GUID that JSGEX currently detects (in 'Device Information').

Device Name, Axis Count, Buttons Count, Hat Count, Vendor ID, Product ID ... could all be stored into the XML Profile file for each device.
Additionally a JSGEX or User-Defined ID could be entered (much like the Label field) in order to allow some control over identification of the device.

If all above criteria are met between the XML Profile Information and the JSGEX Application's data for a device except the GUID, then the user would be prompted for the Repair Profile function.
This is where JSGEX would replace the old GUID # with the new GUID # for the changed device in the XML Profile

------------------------------------------------------------------------------------

The JSGEX Application could perform the GUID check on profile load up, as well as either recheck when the GUID changes (_if it can sense GUID changes pushed down to it {represented within 'device information'}_), or poll every few seconds to compare the GUIDs it can see to the ones within the loaded XML Profile.

**Comment by muchimi** [comment]
The actions menu swap device provides functionality to map one hardware device to the other.
I don't think automation will work here because of the challenges it may create if the wrong device is used.  I also think this is a very rare use-case so I'll put it on the research list but I'm not planning to do anything with this currently until the other higher priorities such as bug fixes and input/output modules are completed.

**Comment by muchimi** [comment]
See device substitution feature - may not be the complete answer.

https://github.com/muchimi/JoystickGremlinEx/issues/62#issuecomment-2294875526

**Comment by muchimi** [comment]
I'll close the issue for now unless something else comes up.
There's a new profile import feature now that lets you load data from another profile into a current profile, and that is XML based so should be much more resilient to items broken, provided the XML is not malformed.
If the XMl is malformed or data is missing, there is not going to be much we can do if data is missing or cannot be read if the file is corrupt.  That should be very rare and usually the result of an issue external to GremlinEx.
