### ISSUE TITLE
[ENHANCEMENT REQUEST] - TEXT TO SPEECH ACTION - Add Volume Control

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#61]
Please consider adding a Volume control to allow the user to specify the output volume in the Text to Speech action, much like what already exists in the Play Sound action.
Thanks!

**Comment by muchimi** [comment]
Volume and rate playback added to TTS starting with 13.14.14ex (patch i for pre-release)
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_i
