### ISSUE TITLE
Error: DualSlider is not Defined

### ISSUE THREAD

**Issue by marcushallett** [muchimi/JoystickGremlinEx#63]
On the latest build (13.40.14ex(k)) there's no way to handle response curves due the error below. I noticed it earlier when I was debugging things in `develop`, last night I think.

It's: `NameError: name 'DualSlider' is not defined`

```
Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 624, in input_item_selected_cb
   File "gremlin\ui\device_tab.py", line 83, in __init__
   File "gremlin\ui\device_tab.py", line 357, in redraw
   File "container_plugins\basic\__init__.py", line 41, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 1397, in __init__
   File "gremlin\ui\input_item.py", line 1418, in _create_action_tab
   File "container_plugins\basic\__init__.py", line 55, in _create_action_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 818, in redraw
   File "C:\tools\JoystickGremlinEX13.40.13ex(m)\_internal\action_plugins\response_curve\__init__.py", line 1049, in __init__
    super().__init__(action_data, parent=parent)
   File "gremlin\ui\input_item.py", line 1600, in __init__
   File "C:\tools\JoystickGremlinEX13.40.13ex(m)\_internal\action_plugins\response_curve\__init__.py", line 1109, in _create_ui
    self.deadzone = DeadzoneWidget(self.action_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\tools\JoystickGremlinEX13.40.13ex(m)\_internal\action_plugins\response_curve\__init__.py", line 906, in __init__
    self.left_slider = DualSlider()
                       ^^^^^^^^^^
 NameError: name 'DualSlider' is not defined
```

It's also impossible to create remappings for hats. The errors have usually been some variation of `'InputItem' object has no attribute 'parent'` or `VjoyRemap` not being iterable. I'll check and see which it's throwing now (been an issue for awhile) and put that in another issue.

**Comment by muchimi** [comment]
Whoops, well, that was me being overly aggressive with code cleanup and removing the control for the response curve.
I've updated release (m).  https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

Let me look into the hat mapping.  Will keep this open as I troubleshoot the hat piece.

**Comment by muchimi** [comment]
Found a couple of bugs issues with hat mapping - was able to map with either remap or vjoy remap and tested ok on my system.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

Pls confirm.

**Comment by muchimi** [comment]
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by marcushallett** [comment]
Excellent. I'll test that tonight.

Also, if you want a hand with published project management, like setting up a GitHub project (or Trello Board, or Jira, or about seven other tools I'm comfortable with) for development use or just for sharing _(potential)_ roadmaps_ with users, please let me know.

The same goes for creating public documentation, user guides in whatever format preferred (anything better than a GitHub wiki—I hate navigating through those to find information I need).

Just shoot me an [email \(this mailto like is convenient\)](mailto:inquiryfrom+muchimi@marcushallett.com&subject=JoystickGremlinEX).

inquiryfrom+muchimi@marcushallett@com
OR
inquiries@marcushallett.com with JoystickGremlin or JoystickGremlinEX somewhere in the subject line.

_IFF_ I think any of the tweaks I'm making for my personal use seem like something others might want _AND_ am satisfied that they are stable enough for production use, I may end up submitting a PR.

**Comment by muchimi** [comment]
Thanks.  Haven't graduated to super fancy yet, I'm aware the project could be improved and I may reach out when the code's feature set is stable.  The documentation in the readme should be enough to get started.
We've had a few folks do PRs already however still "stuck" on getting the current feature set for 13.40.14ex stable to be pushed to the main branch as a full release.  I do appreciate the offer.

**Comment by marcushallett** [comment]
No problem.  Happy to lend a hand if desired.



--
Marcus Taylor Hallett
***@***.***
2024-08-19 21:02Z
________________________________
