### ISSUE TITLE
13.40.14ex (m) - Error while loading plugin

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#64]
Hi,

The following error was displayed when trying to import VPC_leds.py module (attached) : 
![image](https://github.com/user-attachments/assets/b3b6cb7b-d993-4a3b-b64b-7648016bd07c)

Plugin: 
[VPC_LEDs.zip](https://github.com/user-attachments/files/16650366/VPC_LEDs.zip)

**Comment by Lolo401** [comment]
Test conditions:
![image](https://github.com/user-attachments/assets/cefaeabe-ddfd-402e-acfe-463f0d55b168)
![image](https://github.com/user-attachments/assets/5d719a1a-377f-40f1-a041-afc691c68bc0)
![image](https://github.com/user-attachments/assets/9b73f692-bf55-40d1-9376-5d11ba60502b)
![image](https://github.com/user-attachments/assets/d98eb5c4-8af6-44f8-b706-7bbd99c62aac)
![image](https://github.com/user-attachments/assets/8716000c-6175-4e79-8228-d0f840279b9b)

Running software at time of test:
VJoy 2.1.9
HidHide 1.5.23.0
OBS 30.2.3

Python installation: 3.12 (64bit)

**Comment by muchimi** [comment]
This is resolved in the incoming patch.

**Comment by muchimi** [comment]
Tested with VPC_LED on my system but this was impacting other plugins as well.
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
