### ISSUE TITLE
13.40.14ex (m) - Error when attempting to delete a MIDI input

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#65]
Hi,

A blank profile was created for testing of the new interface.  The MIDI tab was accessed and a new MIDI (not configured) input was created.  The delete icon was push to try and delete the newly created input.

The following was displayed:
![image](https://github.com/user-attachments/assets/b780bc90-c0ef-463f-9b0a-187d3457438b)

**Comment by Lolo401** [comment]
The above was tried for an OSC input.
The same message was displayed when trying to delete the newly OSC input.
![image](https://github.com/user-attachments/assets/f4dbd317-a253-44b1-aefb-9c72c8b69cf1)

**Comment by Lolo401** [comment]
Test conditions:
Processor: AMD Ryzen 7800X3D
RAM: 64.0GB
OS: Windows 11 Pro 23H2 OS build 22631.4037
Python installation: 3.12 (64bit)

Running software at time of test:
VJoy 2.1.9
HidHide 1.5.23.0
OBS 30.2.3

**Comment by muchimi** [comment]
On it.

**Comment by muchimi** [comment]
This has been resolved in the next patch.

**Comment by muchimi** [comment]
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
