### ISSUE TITLE
13.40.14ex (m) - Unable to merge axis

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#66]
A blank profile was created.  Two axis were mapped using Remap on a device.
The menu/Actions/Merge axis option was selected and 'New axis' was pushed.
The following was displayed:
![image](https://github.com/user-attachments/assets/9baa554d-38ea-40e9-b5f3-d4ad4921ea41)

**Comment by Lolo401** [comment]
Test conditions:
Processor: AMD Ryzen 7800X3D
RAM: 64.0GB
OS: Windows 11 Pro 23H2 OS build 22631.4037
Python installation: 3.12 (64bit)

Running software at time of test:
VJoy 2.1.9
HidHide 1.5.23.0
OBS 30.2.3

**Comment by muchimi** [comment]
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
