### ISSUE TITLE
13.40.14ex (m) - Sort devices, too many values to unpack

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#67]
The new ID sort feature was tested using a blank profile with the following devices connected and correctly detected:
2x Virpil Prime sticks,
2x Virpil Panels,
1x Virpil CM3 throttle,
1x Thrustmaster cougar throttle,
1x Azeron keypad.

The sort devices option was accessed through the menu and the following was displayed:
![image](https://github.com/user-attachments/assets/6803e459-bd61-4eb0-80b5-2e516548721a)

Of note: Due to prior testing, 1x unconfigured MIDI and 1x OSC input were also present.

**Comment by Lolo401** [comment]
Test conditions:
Processor: AMD Ryzen 7800X3D
RAM: 64.0GB
OS: Windows 11 Pro 23H2 OS build 22631.4037
Python installation: 3.12 (64bit)

Running software at time of test:
VJoy 2.1.9
HidHide 1.5.23.0
OBS 30.2.3

Connected Devices:
Thrustmaster Throttle - HOTAS Warthog
Thrustmaster T-pendular rudder
Virpil Control Panel 1
Virpil Control Panel 2
Virpil Control L-Stick Alpha Prime
Virpil Control R-Stick Alpha Prime
Virpil Control Throttle 50CM3
Azeron Keypad

**Comment by muchimi** [comment]
Proposed fix in upcoming patch

**Comment by muchimi** [comment]
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
