### ISSUE TITLE
13.40.14ex (m) - Software Not responding when using View Input Map

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#68]
The view input map feature was tested using a blank profile with 7 devices connected.  There was no mapping. 
When using the View input map, when clicking the 'By device' box, all devices were detected and displayed.  Two axis were then mapped on the Cougar throttle as Vjoy Device X and Y.

Clicking on the View Input Map, correctly displayed the mapping in 'By mode'.  Clicking on the 'By device' resulted in the following:
(1) JG Ex unrecoverable crash,
(2) High usage on the CPU with the computer slowing down and all fans revving up.

![image](https://github.com/user-attachments/assets/c2c8e906-fac0-4015-80bb-db4a083f1fe3)

The only option was to kill the JG process via the Task Manager
![image](https://github.com/user-attachments/assets/0f0ecb5e-7890-400a-bdfd-0f795f256ac5)

**Comment by Lolo401** [comment]
Test conditions:
Processor: AMD Ryzen 7800X3D
RAM: 64.0GB
OS: Windows 11 Pro 23H2 OS build 22631.4037
Python installation: 3.12 (64bit)

Running software at time of test:
VJoy 2.1.9
HidHide 1.5.23.0
OBS 30.2.3

Connected Devices:
Thrustmaster Throttle - HOTAS Warthog
Thrustmaster T-pendular rudder
Virpil Control Panel 1
Virpil Control Panel 2
Virpil Control L-Stick Alpha Prime
Virpil Control R-Stick Alpha Prime
Virpil Control Throttle 50CM3
Azeron Keypad

**Comment by muchimi** [comment]
This has been resolved in the upcoming patch.

**Comment by muchimi** [comment]
Proposed fix in patch m5: https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
