### ISSUE TITLE
VjoyRemap green/orange balls not updating correctly while in a session

### ISSUE THREAD

**Issue by alex-smtv** [muchimi/JoystickGremlinEx#7]
The issues I'll describe is a UI problem and happens while in a session. If the software is closed and opened back everything is correctly presented.

To make it simple the use case starts with a new empty profile from a random physical button. When creating a VjoyRemap the vJoy button 1 is selected be default and the ball status is orange, no problem here. But then:

1) If I select vJoy button 2 from the radio choices (and not from the list) the ball status doesn't update and stays green. If I select another physical button and come back to the previous physical button where I was configuring VjoyRemap, the ball status of vJoy button 2 updates to orange.

2) Starting from 1), if I switch my choice to another vJoy button (let's say number 3) then the previous selected vJoy button (number 2) will permanently keep it's statue ball in orange in the future. This applies to all future change. Meaning you can have selected only vJoy button 9, but have vJoy button 1 to 5 (as an example) statue balls in orange because they were previously selected (turned orange by the workaround in 1)).

3) Issue 2) persist when creating a new profile. Meaning in a new fresh profile, creating a VjoyRemap will have several statue balls already in orange from previous operations.

**Comment by muchimi** [comment]
I'll investigate - one more QT UI thing going on for sure.  
Thanks for reporting.

**Comment by muchimi** [comment]
This is fixed in 10.40.3 - it was missing an update pass on a radio button change.
