### ISSUE TITLE
13.40.14ex (m5) - Macro's are missing in action

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#70]
After loading a previously created profile, all macro's in the profile were blank.  
![image](https://github.com/user-attachments/assets/f8a457de-a0a7-4260-84b8-f3b62e647a3e)

Also, the macro action appears to have disappeared from the action menu:
![image](https://github.com/user-attachments/assets/cadc99c3-d4d8-408a-bd28-6531fa7be247)

**Comment by muchimi** [comment]
Discovered one cause.  I swear the macro plugin is cursed.

**Comment by muchimi** [comment]
Proposed fix in m6.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
