### ISSUE TITLE
13.40.14ex (m5) - QoL suggestions: resize the device buttons/axis list vertically

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#72]
![image](https://github.com/user-attachments/assets/12a09cf2-e273-4434-b2fd-b4c24c843f71)

Based on using the new release for testing, it was noticed that navigating through the buttons / axis of a device was taking much longer than with .13ex.  Vertically, 8 buttons / axis can be displayed where .13ex would display 21 (based on a side by side comparison).

It would be ideal to reduce the vertical real estate of the fields.  IMHO and probably just something to get used to.

**Comment by muchimi** [comment]
I'll have to do another pass on the UI input widget to coerce QT to not waste all that space - it loves to waste space with this layout and I've so far avoided hardcoding heights but I may end up doing that as the QT sizing logic is not ideal in this scenario.
You don't have the repeaters enabled either - that adds another line.

**Comment by muchimi** [comment]
Input widget has been reworked in m7 and is now a super "compact" form.

**Comment by muchimi** [comment]
Marking as implemented as of 13.40.14ex m7.
