### ISSUE TITLE
13.40.14ex (m5) - Profile Edit Mode not working / not displaying correct mode

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#74]
The modes management was tested using a blank profile.  2 Test modes were created:
![image](https://github.com/user-attachments/assets/b0e6232f-d7b3-480f-93ca-0ae2114aabb8)

It was possible to correctly setup Cycle modes and Switch Mode actions.
![image](https://github.com/user-attachments/assets/cc210d46-aee5-4dc6-b63b-7cc0a1902ce5)

However, it was not possible to switch to another mode for editing, only the default mode was displayed:
![image](https://github.com/user-attachments/assets/ba7d2036-a4c4-4c67-be43-ff230b2b05d2)

The name of the default mode was changed to default test:
![image](https://github.com/user-attachments/assets/7088e09c-edf9-40ef-8bad-93ff13cca23c).

The name was not automatically updated in the Cycle Modes and Switch mode remaps until the option was changed.

**Comment by Lolo401** [comment]
Additional observation:
Opening an existing profile with modes and submodes work as intended.  However, editing a mode name renders the mode inaccessible :

https://github.com/user-attachments/assets/02b42969-49ce-4dcd-841f-8445aaa9c1d2

**Comment by muchimi** [comment]
m7 makes a couple of changes:  (1) forces an update of the main UI edit profile drop down when a mode has been edited to resync the control to the profile data (and yes, it should have done this and didn't).   (2) the edit profile drop down is now disabled when a profile is running to avoid a conflict where configuration changes could be made while a profile is running, leading to a very confused environment.  The dropdown is re-enabled when the profile stops running.

**Comment by muchimi** [comment]
Marking as fixed as of 13.40.14ex m7.  We can re-open if this still has issues.

**Comment by Rolln-dev** [comment]
> Marking as fixed as of 13.40.1 4ex m7. We can re-open if this still has issues.

I actually just ran into this issue.  13.40.14ex(m8)

https://github.com/user-attachments/assets/f8b13652-c4c9-43f6-9e5e-166ee7fa0270
