### ISSUE TITLE
13.40.14ex (m6) - Macros still not reporting for duty .....

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#76]
![image](https://github.com/user-attachments/assets/ab10200a-8806-41b7-8370-4f072937d86d)

Same symptoms as described in the completed issue.

**Comment by muchimi** [comment]
Let's see if other fixes in m7 address this.  I was not able to duplicate it.

**Comment by muchimi** [comment]
And correction - I found a reference not picked up by the packager which prevented in fact a pair of actions from loading, macro and simconnect.  definitely fixed in m7.

**Comment by muchimi** [comment]
Marking as fixed as of 13.40.14ex m7.  We can re-open if this still has issues.
