### ISSUE TITLE
13.40.13(ex) - Unable to change merge axis settings

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#77]
As I was investigating my issue regarding the missing tabs, the following was noticed in .13(ex) but is NOT present in .14ex (m6)
Trying to change the merge axis settings via UI results in a QT error.

13.40.13(ex) error:
![image](https://github.com/user-attachments/assets/33dffaec-10d8-4c34-a393-a266cbeb7af5)

Trying to close JG Ex results in:
![image](https://github.com/user-attachments/assets/6dd789c8-ab54-45eb-91d0-0426e0784f5d)

Full video of the error: (13.40.13ex)
https://github.com/user-attachments/assets/0465c1fa-b6c8-4c1e-9209-0fc0b7dd2289

Although .13ex is soon obsolete, I wanted to post this for your tracking.  Working fine in m6.

**Comment by muchimi** [comment]
Thanks.

**Comment by muchimi** [comment]
Marking this resolved as of m8.
Merge axis functionality is now also available as an action that can be added to any input axis and then map additional actions/containers to the output of the merge action if you need the output curved or gated for example.  Subactions supported are any action that attaches to an axis input.
