### ISSUE TITLE
13.40.14ex (m7) - Unable to load / save plugin data

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#78]
Fixed:
- The plugin (VPC_led.py) now correctly loads and new instances can be created / modified.
- The LED's correctly respond once instance are programmed

Not fixed:
- Save profile: Data's are not saved in the profile.xml file.
- Load profile: Opening a profile with pre-existing instances results in blank or default data being presented in the UI.

Full video:
https://github.com/user-attachments/assets/e4413b6e-45c4-4e28-85a5-936a68294eee

**Comment by Lolo401** [comment]
Content of the profile XML file after the save in the video above showing all data fields blank:
            <instance name="Default">
                <variable name="Virtual input axis" type="VirtualInput" is-optional="False"/>
                <variable name="Button" type="PhysicalInput" is-optional="False"/>
                <variable name="LED Device" type="PhysicalInput" is-optional="False"/>
                <variable name="Mode" type="Mode" is-optional="False"/>
                <variable name="LED numbers" type="String" is-optional="False"/>
                <variable name="Retain state of LEDs until pressed again" type="Bool" is-optional="False"/>
                <variable name="Delay (ms)" type="Int" is-optional="False"/>
                <variable name="Change on input activation" type="Bool" is-optional="False"/>
                <variable name="Activation/Blink primary: Red" type="Int" is-optional="False"/>
                <variable name="Activation/Blink primary: Green" type="Int" is-optional="False"/>
                <variable name="Activation/Blink primary: Blue" type="Int" is-optional="False"/>
                <variable name="Change on input deactivation" type="Bool" is-optional="False"/>
                <variable name="Deactivation: Red" type="Int" is-optional="False"/>
                <variable name="Deactivation: Green" type="Int" is-optional="False"/>
                <variable name="Deactivation: Blue" type="Int" is-optional="False"/>
                <variable name="Blink between LED colour states until deactivated" type="Bool" is-optional="False"/>
                <variable name="Blink button hold or momentary; Hold = checked" type="Bool" is-optional="False"/>
                <variable name="Blink Timer (ms)" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Red" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Green" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Blue" type="Int" is-optional="False"/>
            </instance>
            <instance name="New Instance">
                <variable name="Virtual input axis" type="VirtualInput" is-optional="False"/>
                <variable name="Button" type="PhysicalInput" is-optional="False"/>
                <variable name="LED Device" type="PhysicalInput" is-optional="False"/>
                <variable name="Mode" type="Mode" is-optional="False"/>
                <variable name="LED numbers" type="String" is-optional="False"/>
                <variable name="Retain state of LEDs until pressed again" type="Bool" is-optional="False"/>
                <variable name="Delay (ms)" type="Int" is-optional="False"/>
                <variable name="Change on input activation" type="Bool" is-optional="False"/>
                <variable name="Activation/Blink primary: Red" type="Int" is-optional="False"/>
                <variable name="Activation/Blink primary: Green" type="Int" is-optional="False"/>
                <variable name="Activation/Blink primary: Blue" type="Int" is-optional="False"/>
                <variable name="Change on input deactivation" type="Bool" is-optional="False"/>
                <variable name="Deactivation: Red" type="Int" is-optional="False"/>
                <variable name="Deactivation: Green" type="Int" is-optional="False"/>
                <variable name="Deactivation: Blue" type="Int" is-optional="False"/>
                <variable name="Blink between LED colour states until deactivated" type="Bool" is-optional="False"/>
                <variable name="Blink button hold or momentary; Hold = checked" type="Bool" is-optional="False"/>
                <variable name="Blink Timer (ms)" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Red" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Green" type="Int" is-optional="False"/>
                <variable name="Blink Secondary: Blue" type="Int" is-optional="False"/>
            </instance>

**Comment by Lolo401** [comment]
Additional info:
The plugin appears to be working as per design as the LED's correctly respond to the data.  The save / load is the outstanding issue.

**Comment by Lolo401** [comment]
Additional information.

The same procedure was repeated with the 'Save partial user plugin data' option turned off under Tools / options.
This resulted in not only the data being blank but the instance entries themselves being removed from the profile.xml.

Video:

https://github.com/user-attachments/assets/c30f50f1-fc7c-49d2-bdaf-a66d384fc078

**Comment by Lolo401** [comment]
The following is a recording of CPU use while closing the Options window.  CPU usage is rising to peak 20%

https://github.com/user-attachments/assets/165c8e64-3598-46f5-ba0a-a4fb41d87bde

**Comment by muchimi** [comment]
Please send me a profile xml that has the module configured.  This one is tough to trace through because I don't have the hardware to test with and have no idea what "correct" values are supposed to be (in other words, I have no known working profile to start from in terms of what the data is supposed to look like in the XML.  Keep in mind the plugin is a third-party write for the original release of Gremlin, so it's also quite likely it won't understand all the changes to the core tool, or use a feature that now behaves differently.  This is completely fixable of course.

A note on partial:  A discovery earlier this week, and why partial is now a thing: when partial is turned off,  the base Gremlin code will ignore the data if one variable defined by the third party plugin reports as not configured (which was the prior issue).
If partial is disabled - one parameter it doesn't like will blitz the whole data from the profile including the good data - which isn't right if you ask me - hence the partial option which is enabled by default. 

With a working known profile, it will point to me what's different.

**Comment by Lolo401** [comment]
I tested the feature using the following procedure so you can compare results:

(1) I downloaded an addition plugin from the whitemagic github repository: active_device_switcher.py
https://gist.github.com/WhiteMagic/812289cb98733d445a2f3c972951ca06#file-active_device_switcher-py
(2) I imported, created a new instance called 'test' and programmed those instances like this in JG .13ex:
  (2.1) VPC_LEDs.py
![image](https://github.com/user-attachments/assets/2e47ee78-84ec-4c5f-aa43-bea53f12d709)
  (2.2) Active_device_swither.py:
![image](https://github.com/user-attachments/assets/45b4d18e-78f2-4783-8b25-329145f23f9d)
(3) I saved the profile and opened the file in VsCode, which looked like this:
![image](https://github.com/user-attachments/assets/c08e37a3-a00c-4cce-8b61-770d2fc1c8f9)
(file attached as 13ex_plugin_test.xml)
[13ex_plugin_test.zip](https://github.com/user-attachments/files/16734391/13ex_plugin_test.zip)
--------
(4) I closed JG 13ex and opened jg 14ex
(5) 13ex_plugin_test.xml automatically opened as expected without issues.
(6) The two instances were correctly displayed:
![image](https://github.com/user-attachments/assets/fbe5e6e3-5e6e-4301-8235-c5d51f2d3e4d)

(7) Accessing the two instances displayed this:
  (7.1) VPC_LED, instance 'test': 
![image](https://github.com/user-attachments/assets/cae4de95-8974-4390-89b3-c1f2ca87aa54)
  (7.2) Active_device_switcher.py:
![image](https://github.com/user-attachments/assets/0c43f971-dbb9-4f62-b999-b761d05a8d7f)

Based on the above test, it appears that the problem is not isolated to VPC_LED.py but the same behavior was observed with another plugin.

I hope this test will help you figure out what is going on.

Cheers !

**Comment by Lolo401** [comment]
Not fixed in m9. Same behavior.

**Comment by muchimi** [comment]
> Not fixed in m9. Same behavior.

Won't be in m10 either.  I am still researching this. Thank you for attaching the XML.  User plugins that use the built-in plugin variables will likely all have the same issue.

**Comment by muchimi** [comment]
With the data above, I was able to narrow down the issue and linked it to core changes - specifically a change in enumeration type to make it compatible with JSON that had an inadvertent behavior change on a comparison operator.  I have reworked the plugin logic in light of the enumeration changes and will have an update soon (it now saves and loads user plugin variables).  Proposed fix inbound soon.

**Comment by muchimi** [comment]
Proposed fix in m11 https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
