### ISSUE TITLE
13.40.14ex (m7) - Gated Axis, adding new gate error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#80]
Trying to add a  new gate via right click resulted in the following error:
![image](https://github.com/user-attachments/assets/d9653a25-8804-4ed4-b4ac-f6a4b6dee462)

However, after acknowledging the error, the gate was displayed and could be moved along the axis.

Workaround: Using the Add button correctly creates a gate at the center position.

**Comment by Lolo401** [comment]
Additionally: Clicking the settings wheel next to a created gate resulted in the following error:
![image](https://github.com/user-attachments/assets/c975a38f-f669-4d74-8060-39ebaef3b33d)

**Comment by muchimi** [comment]
Indeed - and it is resolved as it was also impacting the new merge axis plugin.
