### ISSUE TITLE
13.40.14ex (m7) - JG uses over 2Gb of RAM with a blank profile

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#81]
![image](https://github.com/user-attachments/assets/b901d778-3f5e-4ffa-b3e0-a66ed3dd0eaf)

Seems odd to me.

**Comment by Lolo401** [comment]
Notes:
I closed and reponed JG Ex and was unable to replicate the issue.  Peak use was 511.0 Mb with a complex profile.
I re-tried all previously tested issues to try and isolate the memory use.  Including gated axis, simconnect, save partial plugin dat, ...

I did however noticed the following:
The Task manager was kept open next to JG as I was troubleshooting issues.  Initial usage was around 170Mb at launch.
After 10 minutes of messing around JG with the same blank profile, memory usage climbed to 663Mb.  Jumps in memory usage are noticeable whenever the Options menu is opened and closed.  The memory usage never goes down, always goes up.  I'll keep on trying.

**Comment by Lolo401** [comment]
After an additional 5 min of random actions. memory usage is at 670.9Mb

**Comment by Lolo401** [comment]
GOT IT:
Everytime a profile is loaded, the memory usage goes up by 200Mb !
Note: loading a blank profile resulted in an average 80Mb increase
loading a complex profile resulted in an average 200Mb increase

Video:

https://github.com/user-attachments/assets/091f5f74-6074-49c6-bee2-8e069032c76f

**Comment by muchimi** [comment]
That is interesting.  I am unsure of the memory allocation as it's automatic.  "How much is too much memory" is one of the answers to the question in this article on the topic:  https://stackoverflow.com/questions/11002247/how-to-reduce-python-script-memory-usage

A blank profile is a full profile in that it has all the devices, modes, and buttons data, which depending on the devices, is a lot of data.  A complex profile will use more memory because it also has containers/action data, and a blank profile will consume some memory. However, I don't think it will use that much more because action data is typically relatively simple.

QT is a hog - that we know.  Beyond that - it may require additional research to see how to coerce a script to use less memory.

**Comment by muchimi** [comment]
Took a snapshot of what it looks like on my system:
![image](https://github.com/user-attachments/assets/de590d7e-13f9-4554-906c-9eeb1d32cbcb)

**Comment by Lolo401** [comment]
What I found unusual is the fact that memory usage was not going down when a profile was either closed or replace by a complex one.  Opening in sequence keeps on adding, as if the previous profile was still being stored in memory.

Since JG Ex users typically load a profile once, I don't think this is a high prio issue.  It only became apparent through testing since profiles are closed / opened repeatedly.

**Comment by muchimi** [comment]
Progress update: After doing some experimentation, this could be related to the QT framework not releasing widgets (QT objects) as those are not necessarily subject to Python garbage collection.

**Comment by muchimi** [comment]
More updates:  I think this is definitely a QT issue not freeing up UI references as I've changed the logic to blitz and re-create the UI on profile load, and the memory footprint while it increases a little on a new profile load is largely improved based on my tests (used to be 100mb per load, now it more or less stays the same).  There may be more to do there - the change will be published in m9.

**Comment by muchimi** [comment]
Improvements in m9 https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by muchimi** [comment]
Marking this as mitigated as of m9 by forcing the profile UI to reset and reload in QT to remove any dangling references not caught by QT's memory manager.  We can reopen if memory increases again.
