### ISSUE TITLE
13.40.14ex (m8) - Fresh install throws errors and hangs.

### ISSUE THREAD

**Issue by Rolln-dev** [muchimi/JoystickGremlinEx#82]
Completely fresh install of 13.40.14ex (m8) (with no previous `~/Joystick Gremlin Ex` folder).
- Throws 2 error popups.
- Sits in the `systray` but doesn't ever open.
- Have to kill process with task manager.
- It does create a new Joystick Gremlin Ex folder with a few files.

![Screenshot 2024-08-24 133943](https://github.com/user-attachments/assets/af48444e-c4d1-4f3a-a6e9-1bb29db16de6)

![Screenshot 2024-08-24 134002](https://github.com/user-attachments/assets/dbed971a-8c3b-4e7e-ba0e-c6d94f2ae9f0)

![Screenshot 2024-08-24 134043](https://github.com/user-attachments/assets/6ba77a76-7e1a-42c5-ae8d-e6b7b2b12648)

![Screenshot 2024-08-24 134105](https://github.com/user-attachments/assets/1e5ff74f-8e7e-4a67-9687-24c14519871a)

![Screenshot 2024-08-24 134806](https://github.com/user-attachments/assets/0f93c3c8-a005-432e-8545-832d2410d21a)

**Comment by Rolln-dev** [comment]
Assume it has something to do with populating the modes drop down list but no modes have been created anywhere yet.  Could be wrong...

**Comment by muchimi** [comment]
On it, thanks.

**Comment by muchimi** [comment]
I'm going to publish m9 shortly once I do some final checks.  M9 resolves an issue with a new profile that could cause this.
I ran a quick test by deleting the configuration folder and did not encounter the load error so I am going with - the default profile mode fix also fixes this.
Soon (tm)

**Comment by Rolln-dev** [comment]
OK.

If I put a blank default mode entry for each device do you think that will get me past the errors temporarily?

**Comment by muchimi** [comment]
Proposed fix in m9 https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by Rolln-dev** [comment]
Fixed!

**Comment by Rolln-dev** [comment]
Fixed!
