### ISSUE TITLE
13.40.14ex (m9) - Not passing button presses to vJoy Device

### ISSUE THREAD

**Issue by Rolln-dev** [muchimi/JoystickGremlinEx#83]
When activating the profile, button presses do not get sent to the vJoy device.  
- Axis work, but buttons do not.
- I tested m8 with same profile and both buttons and axis work.

https://github.com/user-attachments/assets/ba1621a6-4a83-4b2c-8231-089d85969eed

**Comment by muchimi** [comment]
Resolved and tested for both legacy remap and vjoyremap as of M10.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by Rolln-dev** [comment]
Fixed!
