### ISSUE TITLE
13.40.14ex (m10) - Cannot add some containers

### ISSUE THREAD

**Issue by Rolln-dev** [muchimi/JoystickGremlinEx#84]
Issues adding some plugin containers

https://github.com/user-attachments/assets/454a82df-703d-4b45-9187-87f61ffb2432

**Comment by Rolln-dev** [comment]
Actually ran into the same issue when adding a `Cycle Modes` action.  Worked ok until I added a condition.

![Screenshot 2024-08-26 091436](https://github.com/user-attachments/assets/54f71a0c-c448-4f2f-9815-6e6444be17e9)
![Screenshot 2024-08-26 091449](https://github.com/user-attachments/assets/3e143797-6b54-4ca4-9ad1-6c80873e7c6b)

**Comment by muchimi** [comment]
Ok thanks.  Actions are tied to the input type, so actions that are axis only will only show for axis inputs, actions that are button only will only show for buttons.  Same for containers.  From that standpoint, not all will show based on what the input is. There were lots of changes around modes.  I'll post an update soon.  Thanks for reporting.

**Comment by Rolln-dev** [comment]
Your welcome.  Thanks for all the work you do!

**Comment by Rolln-dev** [comment]
Also, when I added a button container and the odd time it would work without error, it did not trigger the release button action.  Press action seemed to work always.

**Comment by muchimi** [comment]
Proposed fix in m11 https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m

**Comment by Rolln-dev** [comment]
Fixed!
