### ISSUE TITLE
13.40.14ex (m11) - After disabling Joystick Gremlin EX, `Profile Edit Mode` always returns to Default

### ISSUE THREAD

**Issue by Rolln-dev** [muchimi/JoystickGremlinEx#85]
Steps to recreate:
- Start editing any mode.
- Enabled Joystick Gremlin to test.
- Disable Joystick Gremlin.

When you disable Joystick gremlin, the mode changes back to `Default` and does not remain on the mode that you were previously editing.  The `Profile Edit Mode` drop down in the top right is still showing the previous mode that you were editing but the main screen is actually back to all the `Default` mode settings.  You then have to select `Default` from the mode drop down and re-select the previous mode to continue editing.

https://github.com/user-attachments/assets/ba30dac9-b78b-46f8-a0c3-229eaa8983ce

**Comment by muchimi** [comment]
Thanks for reporting.

**Comment by Rolln-dev** [comment]
For sure.

**Comment by muchimi** [comment]
Resolved in m12 via new mode handling refractor.
https://github.com/muchimi/JoystickGremlinEx/releases/tag/13.40.14ex_m
