### ISSUE TITLE
JG 13.40.14ex (m11) - Some Vjoy devices stop responding after 10 min of use

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#87]
This one is a tricky one as it hard to replicate.  I will provide additional information with recordings but here is what I observed:

(1) The profile was opened and everything appeared as per design.
(2) After 10 min, it was realized that the left stick (bound to VJoy2) was no longer responding.
(3) Alt-tabbing to JG Ex displayed a blank profile where the bindings were supposed to be shown.
(4) The Profile Edit Mode displayed 'default' as mode, which was never programmed in the profile.
(5) Disabling the profile resulted in the following error:
![image](https://github.com/user-attachments/assets/284b843c-03e9-4de2-af51-72cb09a21232)

(6) Trying to delete the 'default' mode in the mode manager resulted in this error:
![image](https://github.com/user-attachments/assets/5c21c0db-06b1-49d6-b9e4-f21e3363f887)

(7) Every action in JG Ex was slower than usual resulting in a windows 'wheel' getting displayed next to the mouse cursor.l

It appears that at some point, JG Ex switched to this 'default' mode and stopped responding.  I will keep investigating and try to replicate the issue consistently.

**Comment by Lolo401** [comment]
JG Ex was closed and re-opened.
The first action was to try and delete the 'default' mode which in this case produced another error:
![image](https://github.com/user-attachments/assets/73fb112a-2cc0-461a-9454-23eb51befec5)

Ackowledging the error would cause the pop-up to reappear continuously.  The only option was to kill JG Ex via the task manager.

**Comment by Lolo401** [comment]
Interesting finding:
(1) A blank profile was created.
(2) The 'default' profile was renamed to 'test' in the mode manager.
(3) The Profile edit mode correctly displayed a single mode 'test'
(3) The profile was saved as test.xml with no bindings.
(4) JG Ex was closed and reopened.
(5) 2 modes were now available in the Profile Edit Mode: Test and a newly created Default.

**Comment by muchimi** [comment]
I suspect the mode refactor will help some of this as far as the incorrect mode being saved or called up - one long running issue is what the UI was showing/displaying was not the actual mode.

As far as VJOY not responding - could be related to the reset pieces on the other issue.  I did a fairly long session and didn't lose any VJOY devices.  To monitor for sure.

**Comment by Lolo401** [comment]
I've noticed an auto change in the local / broadcast mode when it occured a second time. The local control got deactivated.  Might be fact fingers on my side.  I'll keep testing.

**Comment by muchimi** [comment]
The initial error was due to a reference error that has been corrected and may lead to subsequent behavior issues (preventing subsequent updates from happening).
I'm going to mark it complete for now.
