### ISSUE TITLE
13.40.14ex (m14) - Gated axis: Not using 'Default range' causes error when adding or removing new gates

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#89]
If 'Use default range for axis output' is unboxed:
![image](https://github.com/user-attachments/assets/4fda4726-7f8c-4988-b44e-eeeccc22d951)

Then trying to change a gate position by clicking on it resulted in the following error:
![image](https://github.com/user-attachments/assets/3d989589-a315-4595-92f3-93594bbe167d)

**Comment by muchimi** [comment]
Resolved in m15.
