### ISSUE TITLE
13.40.14ex (m14) - Adding range events causes error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#90]
A blank profile was created.  A Gated Axis was assigned to one axis and a third gate was inserted to create 2 ranges.  The intent was to have the gate act as a Toggle: above the gate, VJOY btn 1 would be pressed, below the gate VJOY btn 2 would be released.

The wheel next to Range 1 was pushed and macro was selected as a new action.

The following error was immediately displayed:
![image](https://github.com/user-attachments/assets/8f252a13-31fb-447b-87f9-2ee813375aee)

**Comment by muchimi** [comment]
The action was refactored in m15.
