### ISSUE TITLE
13.40.14ex (m14) - Creating a new profile with an existing profile opened does not clear the profile edit mode list

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#96]
![image](https://github.com/user-attachments/assets/cb9d1069-07f7-44f4-8c91-f7f7cad72b86)
![image](https://github.com/user-attachments/assets/e95edc43-5794-417a-9ce7-3035d09b5358)

As per the image, a new blank profile was created with File/new profile while the previous was opened.
All modes transferred to the new profile in the list although the 'manage mode' window only shows Default.
Default was not available in the list although the Runtime mode and Edit mode show default as active.
![image](https://github.com/user-attachments/assets/c58a90b9-e6d2-41f2-b28d-0fd252086fad)

**Comment by Lolo401** [comment]
Workaround:

Close and reopen JG Ex after saving the new profile.  This will clear the list.

**Comment by muchimi** [comment]
Fixed in m15.
