### ISSUE TITLE
13.40.14ex (m14) - Create 1/1 mapping does not work, sets VJoy1/Axis1 to all axis and VJoy1/Button1 to all buttons

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#97]
The 1/1 mapping feature was tested on a blank profile.
It resulted in all buttons of the physical used for testing being mapped to VJOY1/Btn1 and all axis to VJOY1/Axis1:
![image](https://github.com/user-attachments/assets/0a1b6dc8-3a8d-4d39-a536-68ab52be43e0)
![image](https://github.com/user-attachments/assets/78e9cb45-6b3a-4f7d-8e30-57a11a7805da)
![image](https://github.com/user-attachments/assets/2a9fa20c-ad12-4b75-b151-b6f248112a13)
![image](https://github.com/user-attachments/assets/1374252a-bb2b-4d9f-b2a0-4e056fb22ee0)

**Comment by muchimi** [comment]
Resolved in m15.  Also changed the behavior so it populates the selected tab, not the first device.
