### ISSUE TITLE
13.40.14ex (m14) - Swap Devices causes error

### ISSUE THREAD

**Issue by Lolo401** [muchimi/JoystickGremlinEx#98]
The swap device was tested on a blank profile with 2 devices (L and R Stick).

The initial Swap device screen was not intuitive:
![image](https://github.com/user-attachments/assets/96f6e5d7-c76d-4bd3-a305-ed8e4ff2f803)
It was not apparent how to perform the swap, there was no button or option.

When trying to change the assignment of one of the sticks, a pop-up appeared asking the user to select the desired axis button or hat.  This was understood as 'activate the device to which the mapping has to be swapped'.  When activating any function on this device, the following error popped up:
![image](https://github.com/user-attachments/assets/6d229fec-eac6-4d12-bdd0-9747609cfa24)

**Comment by muchimi** [comment]
Resolved in m15
